import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  AIConfiguration,
  AIConversation,
  AIMessage,
  Client,
  ClientReliefPeriod,
  ClientSuspension,
  Company,
  CompanyModuleAccess,
  DocumentTemplate,
  EmailAutoReplyTemplate,
  GeneratedDocument,
  Lead,
  Module as ModuleEntity,
  MonthlySettlement,
  Notification,
  Offer,
  OfferActivity,
  OfferTemplate,
  SettlementComment,
  SettlementSettings,
  Task,
  TaskComment,
  TaskDependency,
  TaskLabel,
  TaskLabelAssignment,
  TimeEntry,
  TimeSettings,
  TokenUsage,
  User,
  UserModulePermission,
} from '@accounting/common';

import { DemoDataSeederService } from './demo-data-seeder.service';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      User,
      Company,
      ModuleEntity,
      CompanyModuleAccess,
      UserModulePermission,
      Client,
      ClientSuspension,
      ClientReliefPeriod,
      Task,
      TaskLabel,
      TaskLabelAssignment,
      TaskDependency,
      TaskComment,
      TimeEntry,
      TimeSettings,
      MonthlySettlement,
      SettlementComment,
      SettlementSettings,
      Lead,
      OfferTemplate,
      Offer,
      OfferActivity,
      DocumentTemplate,
      GeneratedDocument,
      Notification,
      EmailAutoReplyTemplate,
      AIConfiguration,
      AIConversation,
      AIMessage,
      TokenUsage,
    ]),
  ],
  providers: [DemoDataSeederService],
  exports: [DemoDataSeederService],
})
export class DemoDataSeedersModule {}
