/**
 * PKD 2025 - Polska Klasyfikacja Działalności
 * Pełna lista 659 kodów PKD na poziomie klasy (5-cyfrowe kody)
 */

import { type PkdClass } from './pkd-codes';

export const PKD_CLASSES: PkdClass[] = [
  {
    code: '01.11.Z',
    name: 'Uprawa zbóż, roślin strączkowych i roślin oleistych na nasiona, z wyłączeniem ryżu',
    division: '01',
    section: 'A',
  },
  { code: '01.12.Z', name: 'Uprawa ryżu', division: '01', section: 'A' },
  {
    code: '01.13.Z',
    name: 'Uprawa warzyw, włączając melony oraz uprawa roślin korzeniowych i roślin bulwiastych',
    division: '01',
    section: 'A',
  },
  { code: '01.14.Z', name: 'Uprawa trzciny cukrowej', division: '01', section: 'A' },
  { code: '01.15.Z', name: 'Uprawa tytoniu', division: '01', section: 'A' },
  { code: '01.16.Z', name: 'Uprawa roślin włóknistych', division: '01', section: 'A' },
  {
    code: '01.19.Z',
    name: 'Pozostałe uprawy rolne inne niż wieloletnie',
    division: '01',
    section: 'A',
  },
  { code: '01.21.Z', name: 'Uprawa winogron', division: '01', section: 'A' },
  {
    code: '01.22.Z',
    name: 'Uprawa drzew i krzewów owocowych tropikalnych i podzwrotnikowych',
    division: '01',
    section: 'A',
  },
  {
    code: '01.23.Z',
    name: 'Uprawa drzew i krzewów owocowych cytrusowych',
    division: '01',
    section: 'A',
  },
  {
    code: '01.24.Z',
    name: 'Uprawa drzew i krzewów owocowych ziarnkowych i pestkowych',
    division: '01',
    section: 'A',
  },
  {
    code: '01.25.Z',
    name: 'Uprawa pozostałych drzew i krzewów owocowych oraz orzechów',
    division: '01',
    section: 'A',
  },
  { code: '01.26.Z', name: 'Uprawa drzew oleistych', division: '01', section: 'A' },
  {
    code: '01.27.Z',
    name: 'Uprawa roślin wykorzystywanych do produkcji napojów',
    division: '01',
    section: 'A',
  },
  {
    code: '01.28.Z',
    name: 'Uprawa roślin przyprawowych i aromatycznych oraz roślin wykorzystywanych do produkcji leków i wyrobów farmaceutycznych',
    division: '01',
    section: 'A',
  },
  { code: '01.29.Z', name: 'Uprawa pozostałych roślin wieloletnich', division: '01', section: 'A' },
  { code: '01.30.Z', name: 'Rozmnażanie roślin', division: '01', section: 'A' },
  { code: '01.41.Z', name: 'Chów i hodowla bydła mlecznego', division: '01', section: 'A' },
  {
    code: '01.42.Z',
    name: 'Chów i hodowla pozostałego bydła i bawołów',
    division: '01',
    section: 'A',
  },
  {
    code: '01.43.Z',
    name: 'Chów i hodowla koni i pozostałych zwierząt koniowatych',
    division: '01',
    section: 'A',
  },
  {
    code: '01.44.Z',
    name: 'Chów i hodowla wielbłądów i zwierząt wielbłądowatych',
    division: '01',
    section: 'A',
  },
  { code: '01.45.Z', name: 'Chów i hodowla owiec i kóz', division: '01', section: 'A' },
  { code: '01.46.Z', name: 'Chów i hodowla świń', division: '01', section: 'A' },
  { code: '01.47.Z', name: 'Chów i hodowla drobiu', division: '01', section: 'A' },
  { code: '01.49.Z', name: 'Chów i hodowla pozostałych zwierząt', division: '01', section: 'A' },
  {
    code: '01.50.Z',
    name: 'Uprawy rolne połączone z chowem i hodowlą zwierząt (działalność mieszana)',
    division: '01',
    section: 'A',
  },
  {
    code: '01.61.Z',
    name: 'Działalność usługowa wspomagająca produkcję roślinną',
    division: '01',
    section: 'A',
  },
  {
    code: '01.62.Z',
    name: 'Działalność usługowa wspomagająca chów i hodowlę zwierząt gospodarskich',
    division: '01',
    section: 'A',
  },
  {
    code: '01.63.Z',
    name: 'Działalność usługowa następująca po zbiorach',
    division: '01',
    section: 'A',
  },
  {
    code: '01.64.Z',
    name: 'Obróbka nasion dla celów rozmnażania roślin',
    division: '01',
    section: 'A',
  },
  {
    code: '01.70.Z',
    name: 'Łowiectwo i pozyskiwanie zwierząt łownych, włączając działalność usługową',
    division: '01',
    section: 'A',
  },
  {
    code: '02.10.Z',
    name: 'Gospodarka leśna i pozostała działalność leśna, z wyłączeniem pozyskiwania produktów leśnych',
    division: '02',
    section: 'A',
  },
  { code: '02.20.Z', name: 'Pozyskiwanie drewna', division: '02', section: 'A' },
  {
    code: '02.30.Z',
    name: 'Pozyskiwanie dziko rosnących produktów leśnych, z wyłączeniem drewna',
    division: '02',
    section: 'A',
  },
  {
    code: '02.40.Z',
    name: 'Działalność usługowa związana z leśnictwem',
    division: '02',
    section: 'A',
  },
  { code: '03.11.Z', name: 'Rybołówstwo w wodach morskich', division: '03', section: 'A' },
  { code: '03.12.Z', name: 'Rybołówstwo w wodach śródlądowych', division: '03', section: 'A' },
  {
    code: '03.21.Z',
    name: 'Chów i hodowla ryb oraz pozostałych organizmów wodnych w wodach morskich',
    division: '03',
    section: 'A',
  },
  {
    code: '03.22.Z',
    name: 'Chów i hodowla ryb oraz pozostałych organizmów wodnych w wodach śródlądowych',
    division: '03',
    section: 'A',
  },
  { code: '05.10.Z', name: 'Wydobywanie węgla kamiennego', division: '05', section: 'B' },
  { code: '05.20.Z', name: 'Wydobywanie węgla brunatnego (lignitu)', division: '05', section: 'B' },
  { code: '06.10.Z', name: 'Górnictwo ropy naftowej', division: '06', section: 'B' },
  { code: '06.20.Z', name: 'Górnictwo gazu ziemnego', division: '06', section: 'B' },
  { code: '07.10.Z', name: 'Górnictwo rud żelaza', division: '07', section: 'B' },
  { code: '07.21.Z', name: 'Górnictwo rud uranu i toru', division: '07', section: 'B' },
  {
    code: '07.29.Z',
    name: 'Górnictwo pozostałych rud metali nieżelaznych',
    division: '07',
    section: 'B',
  },
  {
    code: '08.11.Z',
    name: 'Wydobywanie kamieni ozdobnych oraz kamienia dla potrzeb budownictwa, skał wapiennych, gipsu, kredy i łupków',
    division: '08',
    section: 'B',
  },
  {
    code: '08.12.Z',
    name: 'Wydobywanie żwiru i piasku; wydobywanie gliny i kaolinu',
    division: '08',
    section: 'B',
  },
  {
    code: '08.91.Z',
    name: 'Wydobywanie minerałów dla przemysłu chemicznego oraz do produkcji nawozów',
    division: '08',
    section: 'B',
  },
  { code: '08.92.Z', name: 'Wydobywanie torfu', division: '08', section: 'B' },
  { code: '08.93.Z', name: 'Wydobywanie soli', division: '08', section: 'B' },
  {
    code: '08.99.Z',
    name: 'Pozostałe górnictwo i wydobywanie, gdzie indziej niesklasyfikowane',
    division: '08',
    section: 'B',
  },
  {
    code: '09.10.Z',
    name: 'Działalność usługowa wspomagająca eksploatację złóż ropy naftowej i gazu ziemnego',
    division: '09',
    section: 'B',
  },
  {
    code: '09.90.Z',
    name: 'Działalność usługowa wspomagająca pozostałe górnictwo i wydobywanie',
    division: '09',
    section: 'B',
  },
  {
    code: '10.11.Z',
    name: 'Przetwarzanie i konserwowanie mięsa, z wyłączeniem mięsa z drobiu',
    division: '10',
    section: 'C',
  },
  {
    code: '10.12.Z',
    name: 'Przetwarzanie i konserwowanie mięsa z drobiu',
    division: '10',
    section: 'C',
  },
  {
    code: '10.13.Z',
    name: 'Produkcja wyrobów z mięsa, włączając wyroby z mięsa drobiowego',
    division: '10',
    section: 'C',
  },
  {
    code: '10.20.Z',
    name: 'Przetwarzanie i konserwowanie ryb, skorupiaków i mięczaków',
    division: '10',
    section: 'C',
  },
  {
    code: '10.31.Z',
    name: 'Przetwarzanie i konserwowanie ziemniaków',
    division: '10',
    section: 'C',
  },
  { code: '10.32.Z', name: 'Produkcja soków z owoców i warzyw', division: '10', section: 'C' },
  {
    code: '10.39.Z',
    name: 'Pozostałe przetwarzanie i konserwowanie owoców i warzyw',
    division: '10',
    section: 'C',
  },
  {
    code: '10.41.Z',
    name: 'Produkcja olejów i pozostałych tłuszczów płynnych',
    division: '10',
    section: 'C',
  },
  {
    code: '10.42.Z',
    name: 'Produkcja margaryny i podobnych tłuszczów jadalnych',
    division: '10',
    section: 'C',
  },
  { code: '10.51.Z', name: 'Przetwórstwo mleka i wyrób serów', division: '10', section: 'C' },
  { code: '10.52.Z', name: 'Produkcja lodów', division: '10', section: 'C' },
  { code: '10.61.Z', name: 'Wytwarzanie produktów przemiału zbóż', division: '10', section: 'C' },
  {
    code: '10.62.Z',
    name: 'Wytwarzanie skrobi i wyrobów skrobiowych',
    division: '10',
    section: 'C',
  },
  {
    code: '10.71.Z',
    name: 'Produkcja pieczywa; produkcja świeżych wyrobów ciastkarskich i ciastek',
    division: '10',
    section: 'C',
  },
  {
    code: '10.72.Z',
    name: 'Produkcja sucharów i herbatników; produkcja konserwowanych wyrobów ciastkarskich i ciastek',
    division: '10',
    section: 'C',
  },
  {
    code: '10.73.Z',
    name: 'Produkcja makaronów, klusek, kuskusu i podobnych wyrobów mącznych',
    division: '10',
    section: 'C',
  },
  { code: '10.81.Z', name: 'Produkcja cukru', division: '10', section: 'C' },
  {
    code: '10.82.Z',
    name: 'Produkcja kakao, czekolady i wyrobów cukierniczych',
    division: '10',
    section: 'C',
  },
  { code: '10.83.Z', name: 'Przetwórstwo herbaty i kawy', division: '10', section: 'C' },
  { code: '10.84.Z', name: 'Produkcja przypraw', division: '10', section: 'C' },
  { code: '10.85.Z', name: 'Wytwarzanie gotowych posiłków i dań', division: '10', section: 'C' },
  {
    code: '10.86.Z',
    name: 'Produkcja artykułów spożywczych homogenizowanych i żywności dietetycznej',
    division: '10',
    section: 'C',
  },
  {
    code: '10.89.Z',
    name: 'Produkcja pozostałych artykułów spożywczych, gdzie indziej niesklasyfikowana',
    division: '10',
    section: 'C',
  },
  {
    code: '10.91.Z',
    name: 'Produkcja gotowej paszy dla zwierząt gospodarskich',
    division: '10',
    section: 'C',
  },
  {
    code: '10.92.Z',
    name: 'Produkcja gotowej karmy dla zwierząt domowych',
    division: '10',
    section: 'C',
  },
  {
    code: '11.01.Z',
    name: 'Destylowanie, rektyfikowanie i mieszanie alkoholi',
    division: '11',
    section: 'C',
  },
  { code: '11.02.Z', name: 'Produkcja win gronowych', division: '11', section: 'C' },
  {
    code: '11.03.Z',
    name: 'Produkcja cydru i pozostałych win owocowych',
    division: '11',
    section: 'C',
  },
  {
    code: '11.04.Z',
    name: 'Produkcja pozostałych niedestylowanych napojów fermentowanych',
    division: '11',
    section: 'C',
  },
  { code: '11.05.Z', name: 'Produkcja piwa', division: '11', section: 'C' },
  { code: '11.06.Z', name: 'Produkcja słodu', division: '11', section: 'C' },
  {
    code: '11.07.Z',
    name: 'Produkcja napojów bezalkoholowych; produkcja wód mineralnych i pozostałych wód butelkowanych',
    division: '11',
    section: 'C',
  },
  { code: '12.00.Z', name: 'PRODUKCJA WYROBÓW TYTONIOWYCH', division: '12', section: 'C' },
  { code: '13.10.A', name: 'Produkcja przędzy bawełnianej', division: '13', section: 'C' },
  { code: '13.10.B', name: 'Produkcja przędzy wełnianej', division: '13', section: 'C' },
  {
    code: '13.10.C',
    name: 'Produkcja przędzy z włókien chemicznych',
    division: '13',
    section: 'C',
  },
  {
    code: '13.10.D',
    name: 'Produkcja przędzy z pozostałych włókien tekstylnych, włączając produkcję nici',
    division: '13',
    section: 'C',
  },
  { code: '13.20.A', name: 'Produkcja tkanin bawełnianych', division: '13', section: 'C' },
  { code: '13.20.B', name: 'Produkcja tkanin wełnianych', division: '13', section: 'C' },
  { code: '13.20.C', name: 'Produkcja tkanin z włókien chemicznych', division: '13', section: 'C' },
  { code: '13.20.D', name: 'Produkcja pozostałych tkanin', division: '13', section: 'C' },
  { code: '13.30.Z', name: 'Wykończanie wyrobów włókienniczych', division: '13', section: 'C' },
  { code: '13.91.Z', name: 'Produkcja dzianin metrażowych', division: '13', section: 'C' },
  { code: '13.92.Z', name: 'Produkcja gotowych wyrobów tekstylnych', division: '13', section: 'C' },
  { code: '13.93.Z', name: 'Produkcja dywanów i chodników', division: '13', section: 'C' },
  {
    code: '13.94.Z',
    name: 'Produkcja wyrobów powroźniczych, lin, szpagatów i wyrobów sieciowych',
    division: '13',
    section: 'C',
  },
  {
    code: '13.95.Z',
    name: 'Produkcja włóknin i wyrobów wykonanych z włóknin, z wyłączeniem odzieży',
    division: '13',
    section: 'C',
  },
  {
    code: '13.96.Z',
    name: 'Produkcja pozostałych technicznych i przemysłowych wyrobów tekstylnych',
    division: '13',
    section: 'C',
  },
  {
    code: '13.99.Z',
    name: 'Produkcja pozostałych wyrobów tekstylnych, gdzie indziej niesklasyfikowana',
    division: '13',
    section: 'C',
  },
  { code: '14.11.Z', name: 'Produkcja odzieży skórzanej', division: '14', section: 'C' },
  { code: '14.12.Z', name: 'Produkcja odzieży roboczej', division: '14', section: 'C' },
  {
    code: '14.13.Z',
    name: 'Produkcja pozostałej odzieży wierzchniej',
    division: '14',
    section: 'C',
  },
  { code: '14.14.Z', name: 'Produkcja bielizny', division: '14', section: 'C' },
  {
    code: '14.19.Z',
    name: 'Produkcja pozostałej odzieży i dodatków do odzieży',
    division: '14',
    section: 'C',
  },
  { code: '14.20.Z', name: 'Produkcja wyrobów futrzarskich', division: '14', section: 'C' },
  { code: '14.31.Z', name: 'Produkcja wyrobów pończoszniczych', division: '14', section: 'C' },
  { code: '14.39.Z', name: 'Produkcja pozostałej odzieży dzianej', division: '14', section: 'C' },
  {
    code: '15.11.Z',
    name: 'Wyprawa skór, garbowanie; wyprawa i barwienie skór futerkowych',
    division: '15',
    section: 'C',
  },
  {
    code: '15.12.Z',
    name: 'Produkcja toreb bagażowych, toreb ręcznych i podobnych wyrobów kaletniczych; produkcja wyrobów rymarskich',
    division: '15',
    section: 'C',
  },
  { code: '15.20.Z', name: 'Produkcja obuwia', division: '15', section: 'C' },
  { code: '16.10.Z', name: 'Produkcja wyrobów tartacznych', division: '16', section: 'C' },
  {
    code: '16.21.Z',
    name: 'Produkcja arkuszy fornirowych i płyt wykonanych na bazie drewna',
    division: '16',
    section: 'C',
  },
  {
    code: '16.22.Z',
    name: 'Produkcja gotowych parkietów podłogowych',
    division: '16',
    section: 'C',
  },
  {
    code: '16.23.Z',
    name: 'Produkcja pozostałych wyrobów stolarskich i ciesielskich dla budownictwa',
    division: '16',
    section: 'C',
  },
  { code: '16.24.Z', name: 'Produkcja opakowań drewnianych', division: '16', section: 'C' },
  {
    code: '16.29.Z',
    name: 'Produkcja pozostałych wyrobów z drewna; produkcja wyrobów z korka, słomy i materiałów używanych do wyplatania',
    division: '16',
    section: 'C',
  },
  { code: '17.11.Z', name: 'Produkcja masy włóknistej', division: '17', section: 'C' },
  { code: '17.12.Z', name: 'Produkcja papieru i tektury', division: '17', section: 'C' },
  {
    code: '17.21.Z',
    name: 'Produkcja papieru falistego i tektury falistej oraz opakowań z papieru i tektury',
    division: '17',
    section: 'C',
  },
  {
    code: '17.22.Z',
    name: 'Produkcja artykułów gospodarstwa domowego, toaletowych i sanitarnych',
    division: '17',
    section: 'C',
  },
  { code: '17.23.Z', name: 'Produkcja artykułów piśmiennych', division: '17', section: 'C' },
  { code: '17.24.Z', name: 'Produkcja tapet', division: '17', section: 'C' },
  {
    code: '17.29.Z',
    name: 'Produkcja pozostałych wyrobów z papieru i tektury',
    division: '17',
    section: 'C',
  },
  { code: '18.11.Z', name: 'Drukowanie gazet', division: '18', section: 'C' },
  { code: '18.12.Z', name: 'Pozostałe drukowanie', division: '18', section: 'C' },
  {
    code: '18.13.Z',
    name: 'Działalność usługowa związana z przygotowywaniem do druku',
    division: '18',
    section: 'C',
  },
  { code: '18.14.Z', name: 'Introligatorstwo i podobne usługi', division: '18', section: 'C' },
  {
    code: '18.20.Z',
    name: 'Reprodukcja zapisanych nośników informacji',
    division: '18',
    section: 'C',
  },
  { code: '19.10.Z', name: 'Wytwarzanie i przetwarzanie koksu', division: '19', section: 'C' },
  {
    code: '19.20.Z',
    name: 'Wytwarzanie i przetwarzanie produktów rafinacji ropy naftowej',
    division: '19',
    section: 'C',
  },
  { code: '20.11.Z', name: 'Produkcja gazów technicznych', division: '20', section: 'C' },
  { code: '20.12.Z', name: 'Produkcja barwników i pigmentów', division: '20', section: 'C' },
  {
    code: '20.13.Z',
    name: 'Produkcja pozostałych podstawowych chemikaliów nieorganicznych',
    division: '20',
    section: 'C',
  },
  {
    code: '20.14.Z',
    name: 'Produkcja pozostałych podstawowych chemikaliów organicznych',
    division: '20',
    section: 'C',
  },
  { code: '20.15.Z', name: 'Produkcja nawozów i związków azotowych', division: '20', section: 'C' },
  {
    code: '20.16.Z',
    name: 'Produkcja tworzyw sztucznych w formach podstawowych',
    division: '20',
    section: 'C',
  },
  {
    code: '20.17.Z',
    name: 'Produkcja kauczuku syntetycznego w formach podstawowych',
    division: '20',
    section: 'C',
  },
  {
    code: '20.20.Z',
    name: 'Produkcja pestycydów i pozostałych środków agrochemicznych',
    division: '20',
    section: 'C',
  },
  {
    code: '20.30.Z',
    name: 'Produkcja farb, lakierów i podobnych powłok, farb drukarskich i mas uszczelniających',
    division: '20',
    section: 'C',
  },
  {
    code: '20.41.Z',
    name: 'Produkcja mydła i detergentów, środków myjących i czyszczących',
    division: '20',
    section: 'C',
  },
  {
    code: '20.42.Z',
    name: 'Produkcja wyrobów kosmetycznych i toaletowych',
    division: '20',
    section: 'C',
  },
  { code: '20.51.Z', name: 'Produkcja materiałów wybuchowych', division: '20', section: 'C' },
  { code: '20.52.Z', name: 'Produkcja klejów', division: '20', section: 'C' },
  { code: '20.53.Z', name: 'Produkcja olejków eterycznych', division: '20', section: 'C' },
  {
    code: '20.59.Z',
    name: 'Produkcja pozostałych wyrobów chemicznych, gdzie indziej niesklasyfikowana',
    division: '20',
    section: 'C',
  },
  { code: '20.60.Z', name: 'Produkcja włókien chemicznych', division: '20', section: 'C' },
  {
    code: '21.10.Z',
    name: 'Produkcja podstawowych substancji farmaceutycznych',
    division: '21',
    section: 'C',
  },
  {
    code: '21.20.Z',
    name: 'Produkcja leków i pozostałych wyrobów farmaceutycznych',
    division: '21',
    section: 'C',
  },
  {
    code: '22.11.Z',
    name: 'Produkcja opon i dętek z gumy; bieżnikowanie i regenerowanie opon z gumy',
    division: '22',
    section: 'C',
  },
  { code: '22.19.Z', name: 'Produkcja pozostałych wyrobów z gumy', division: '22', section: 'C' },
  {
    code: '22.21.Z',
    name: 'Produkcja płyt, arkuszy, rur i kształtowników z tworzyw sztucznych',
    division: '22',
    section: 'C',
  },
  {
    code: '22.22.Z',
    name: 'Produkcja opakowań z tworzyw sztucznych',
    division: '22',
    section: 'C',
  },
  {
    code: '22.23.Z',
    name: 'Produkcja wyrobów dla budownictwa z tworzyw sztucznych',
    division: '22',
    section: 'C',
  },
  {
    code: '22.29.Z',
    name: 'Produkcja pozostałych wyrobów z tworzyw sztucznych',
    division: '22',
    section: 'C',
  },
  { code: '23.11.Z', name: 'Produkcja szkła płaskiego', division: '23', section: 'C' },
  {
    code: '23.12.Z',
    name: 'Kształtowanie i obróbka szkła płaskiego',
    division: '23',
    section: 'C',
  },
  { code: '23.13.Z', name: 'Produkcja szkła gospodarczego', division: '23', section: 'C' },
  { code: '23.14.Z', name: 'Produkcja włókien szklanych', division: '23', section: 'C' },
  {
    code: '23.19.Z',
    name: 'Produkcja i obróbka pozostałego szkła, włączając szkło techniczne',
    division: '23',
    section: 'C',
  },
  { code: '23.20.Z', name: 'Produkcja wyrobów ogniotrwałych', division: '23', section: 'C' },
  { code: '23.31.Z', name: 'Produkcja ceramicznych kafli i płytek', division: '23', section: 'C' },
  {
    code: '23.32.Z',
    name: 'Produkcja cegieł, dachówek i materiałów budowlanych, z wypalanej gliny',
    division: '23',
    section: 'C',
  },
  {
    code: '23.41.Z',
    name: 'Produkcja ceramicznych wyrobów stołowych i ozdobnych',
    division: '23',
    section: 'C',
  },
  {
    code: '23.42.Z',
    name: 'Produkcja ceramicznych wyrobów sanitarnych',
    division: '23',
    section: 'C',
  },
  {
    code: '23.43.Z',
    name: 'Produkcja ceramicznych izolatorów i osłon izolacyjnych',
    division: '23',
    section: 'C',
  },
  {
    code: '23.44.Z',
    name: 'Produkcja pozostałych technicznych wyrobów ceramicznych',
    division: '23',
    section: 'C',
  },
  {
    code: '23.49.Z',
    name: 'Produkcja pozostałych wyrobów ceramicznych',
    division: '23',
    section: 'C',
  },
  { code: '23.51.Z', name: 'Produkcja cementu', division: '23', section: 'C' },
  { code: '23.52.Z', name: 'Produkcja wapna i gipsu', division: '23', section: 'C' },
  { code: '23.61.Z', name: 'Produkcja wyrobów budowlanych z betonu', division: '23', section: 'C' },
  { code: '23.62.Z', name: 'Produkcja wyrobów budowlanych z gipsu', division: '23', section: 'C' },
  {
    code: '23.63.Z',
    name: 'Produkcja masy betonowej prefabrykowanej',
    division: '23',
    section: 'C',
  },
  { code: '23.64.Z', name: 'Produkcja zaprawy murarskiej', division: '23', section: 'C' },
  { code: '23.65.Z', name: 'Produkcja cementu wzmocnionego włóknem', division: '23', section: 'C' },
  {
    code: '23.69.Z',
    name: 'Produkcja pozostałych wyrobów z betonu, gipsu i cementu',
    division: '23',
    section: 'C',
  },
  {
    code: '23.70.Z',
    name: 'Cięcie, formowanie i wykańczanie kamienia',
    division: '23',
    section: 'C',
  },
  { code: '23.91.Z', name: 'Produkcja wyrobów ściernych', division: '23', section: 'C' },
  {
    code: '23.99.Z',
    name: 'Produkcja pozostałych wyrobów z mineralnych surowców niemetalicznych, gdzie indziej niesklasyfikowana',
    division: '23',
    section: 'C',
  },
  {
    code: '24.10.Z',
    name: 'Produkcja surówki, żelazostopów, żeliwa i stali oraz wyrobów hutniczych',
    division: '24',
    section: 'C',
  },
  {
    code: '24.20.Z',
    name: 'Produkcja rur, przewodów, kształtowników zamkniętych i łączników, ze stali',
    division: '24',
    section: 'C',
  },
  { code: '24.31.Z', name: 'Produkcja prętów ciągnionych na zimno', division: '24', section: 'C' },
  {
    code: '24.32.Z',
    name: 'Produkcja wyrobów płaskich walcowanych na zimno',
    division: '24',
    section: 'C',
  },
  { code: '24.33.Z', name: 'Produkcja wyrobów formowanych na zimno', division: '24', section: 'C' },
  { code: '24.34.Z', name: 'Produkcja drutu', division: '24', section: 'C' },
  { code: '24.41.Z', name: 'Produkcja metali szlachetnych', division: '24', section: 'C' },
  { code: '24.42.A', name: 'Produkcja aluminium hutniczego', division: '24', section: 'C' },
  {
    code: '24.42.B',
    name: 'Produkcja wyrobów z aluminium i stopów aluminium',
    division: '24',
    section: 'C',
  },
  { code: '24.43.Z', name: 'Produkcja ołowiu, cynku i cyny', division: '24', section: 'C' },
  { code: '24.44.Z', name: 'Produkcja miedzi', division: '24', section: 'C' },
  {
    code: '24.45.Z',
    name: 'Produkcja pozostałych metali nieżelaznych',
    division: '24',
    section: 'C',
  },
  { code: '24.46.Z', name: 'Wytwarzanie paliw jądrowych', division: '24', section: 'C' },
  { code: '24.51.Z', name: 'Odlewnictwo żeliwa', division: '24', section: 'C' },
  { code: '24.52.Z', name: 'Odlewnictwo staliwa', division: '24', section: 'C' },
  { code: '24.53.Z', name: 'Odlewnictwo metali lekkich', division: '24', section: 'C' },
  { code: '24.54.A', name: 'Odlewnictwo miedzi i stopów miedzi', division: '24', section: 'C' },
  {
    code: '24.54.B',
    name: 'Odlewnictwo pozostałych metali nieżelaznych, gdzie indziej niesklasyfikowane',
    division: '24',
    section: 'C',
  },
  {
    code: '25.11.Z',
    name: 'Produkcja konstrukcji metalowych i ich części',
    division: '25',
    section: 'C',
  },
  {
    code: '25.12.Z',
    name: 'Produkcja metalowych elementów stolarki budowlanej',
    division: '25',
    section: 'C',
  },
  {
    code: '25.21.Z',
    name: 'Produkcja grzejników i kotłów centralnego ogrzewania',
    division: '25',
    section: 'C',
  },
  {
    code: '25.29.Z',
    name: 'Produkcja pozostałych zbiorników, cystern i pojemników metalowych',
    division: '25',
    section: 'C',
  },
  {
    code: '25.30.Z',
    name: 'Produkcja wytwornic pary, z wyłączeniem kotłów do centralnego ogrzewania gorącą wodą',
    division: '25',
    section: 'C',
  },
  { code: '25.40.Z', name: 'Produkcja broni i amunicji', division: '25', section: 'C' },
  {
    code: '25.50.Z',
    name: 'Kucie, prasowanie, wytłaczanie i walcowanie metali; metalurgia proszków',
    division: '25',
    section: 'C',
  },
  {
    code: '25.61.Z',
    name: 'Obróbka metali i nakładanie powłok na metale',
    division: '25',
    section: 'C',
  },
  {
    code: '25.62.Z',
    name: 'Obróbka mechaniczna elementów metalowych',
    division: '25',
    section: 'C',
  },
  {
    code: '25.71.Z',
    name: 'Produkcja wyrobów nożowniczych i sztućców',
    division: '25',
    section: 'C',
  },
  { code: '25.72.Z', name: 'Produkcja zamków i zawiasów', division: '25', section: 'C' },
  { code: '25.73.Z', name: 'Produkcja narzędzi', division: '25', section: 'C' },
  { code: '25.91.Z', name: 'Produkcja pojemników metalowych', division: '25', section: 'C' },
  { code: '25.92.Z', name: 'Produkcja opakowań z metali', division: '25', section: 'C' },
  {
    code: '25.93.Z',
    name: 'Produkcja wyrobów z drutu, łańcuchów i sprężyn',
    division: '25',
    section: 'C',
  },
  { code: '25.94.Z', name: 'Produkcja złączy i śrub', division: '25', section: 'C' },
  {
    code: '25.99.Z',
    name: 'Produkcja pozostałych gotowych wyrobów metalowych, gdzie indziej niesklasyfikowana',
    division: '25',
    section: 'C',
  },
  { code: '26.11.Z', name: 'Produkcja elementów elektronicznych', division: '26', section: 'C' },
  {
    code: '26.12.Z',
    name: 'Produkcja elektronicznych obwodów drukowanych',
    division: '26',
    section: 'C',
  },
  {
    code: '26.20.Z',
    name: 'Produkcja komputerów i urządzeń peryferyjnych',
    division: '26',
    section: 'C',
  },
  {
    code: '26.30.Z',
    name: 'Produkcja sprzętu (tele)komunikacyjnego',
    division: '26',
    section: 'C',
  },
  {
    code: '26.40.Z',
    name: 'Produkcja elektronicznego sprzętu powszechnego użytku',
    division: '26',
    section: 'C',
  },
  {
    code: '26.51.Z',
    name: 'Produkcja instrumentów i przyrządów pomiarowych, kontrolnych i nawigacyjnych',
    division: '26',
    section: 'C',
  },
  { code: '26.52.Z', name: 'Produkcja zegarków i zegarów', division: '26', section: 'C' },
  {
    code: '26.60.Z',
    name: 'Produkcja urządzeń napromieniowujących, sprzętu elektromedycznego i elektroterapeutycznego',
    division: '26',
    section: 'C',
  },
  {
    code: '26.70.Z',
    name: 'Produkcja instrumentów optycznych i sprzętu fotograficznego',
    division: '26',
    section: 'C',
  },
  {
    code: '26.80.Z',
    name: 'Produkcja magnetycznych i optycznych niezapisanych nośników informacji',
    division: '26',
    section: 'C',
  },
  {
    code: '27.11.Z',
    name: 'Produkcja elektrycznych silników, prądnic i transformatorów',
    division: '27',
    section: 'C',
  },
  {
    code: '27.12.Z',
    name: 'Produkcja aparatury rozdzielczej i sterowniczej energii elektrycznej',
    division: '27',
    section: 'C',
  },
  { code: '27.20.Z', name: 'Produkcja baterii i akumulatorów', division: '27', section: 'C' },
  { code: '27.31.Z', name: 'Produkcja kabli światłowodowych', division: '27', section: 'C' },
  {
    code: '27.32.Z',
    name: 'Produkcja pozostałych elektronicznych i elektrycznych przewodów i kabli',
    division: '27',
    section: 'C',
  },
  { code: '27.33.Z', name: 'Produkcja sprzętu instalacyjnego', division: '27', section: 'C' },
  {
    code: '27.40.Z',
    name: 'Produkcja elektrycznego sprzętu oświetleniowego',
    division: '27',
    section: 'C',
  },
  {
    code: '27.51.Z',
    name: 'Produkcja elektrycznego sprzętu gospodarstwa domowego',
    division: '27',
    section: 'C',
  },
  {
    code: '27.52.Z',
    name: 'Produkcja nieelektrycznego sprzętu gospodarstwa domowego',
    division: '27',
    section: 'C',
  },
  {
    code: '27.90.Z',
    name: 'Produkcja pozostałego sprzętu elektrycznego',
    division: '27',
    section: 'C',
  },
  {
    code: '28.11.Z',
    name: 'Produkcja silników i turbin, z wyłączeniem silników lotniczych, samochodowych i motocyklowych',
    division: '28',
    section: 'C',
  },
  {
    code: '28.12.Z',
    name: 'Produkcja sprzętu i wyposażenia do napędu hydraulicznego i pneumatycznego',
    division: '28',
    section: 'C',
  },
  { code: '28.13.Z', name: 'Produkcja pozostałych pomp i sprężarek', division: '28', section: 'C' },
  { code: '28.14.Z', name: 'Produkcja pozostałych kurków i zaworów', division: '28', section: 'C' },
  {
    code: '28.15.Z',
    name: 'Produkcja łożysk, kół zębatych, przekładni zębatych i elementów napędowych',
    division: '28',
    section: 'C',
  },
  {
    code: '28.21.Z',
    name: 'Produkcja pieców, palenisk i palników piecowych',
    division: '28',
    section: 'C',
  },
  {
    code: '28.22.Z',
    name: 'Produkcja urządzeń dźwigowych i chwytaków',
    division: '28',
    section: 'C',
  },
  {
    code: '28.23.Z',
    name: 'Produkcja maszyn i sprzętu biurowego, z wyłączeniem komputerów i urządzeń peryferyjnych',
    division: '28',
    section: 'C',
  },
  {
    code: '28.24.Z',
    name: 'Produkcja narzędzi ręcznych mechanicznych',
    division: '28',
    section: 'C',
  },
  {
    code: '28.25.Z',
    name: 'Produkcja przemysłowych urządzeń chłodniczych i wentylacyjnych',
    division: '28',
    section: 'C',
  },
  {
    code: '28.29.Z',
    name: 'Produkcja pozostałych maszyn ogólnego przeznaczenia, gdzie indziej niesklasyfikowana',
    division: '28',
    section: 'C',
  },
  {
    code: '28.30.Z',
    name: 'Produkcja maszyn dla rolnictwa i leśnictwa',
    division: '28',
    section: 'C',
  },
  { code: '28.41.Z', name: 'Produkcja maszyn do obróbki metalu', division: '28', section: 'C' },
  {
    code: '28.49.Z',
    name: 'Produkcja pozostałych narzędzi mechanicznych',
    division: '28',
    section: 'C',
  },
  { code: '28.91.Z', name: 'Produkcja maszyn dla metalurgii', division: '28', section: 'C' },
  {
    code: '28.92.Z',
    name: 'Produkcja maszyn dla górnictwa i do wydobywania oraz budownictwa',
    division: '28',
    section: 'C',
  },
  {
    code: '28.93.Z',
    name: 'Produkcja maszyn stosowanych w przetwórstwie żywności, tytoniu i produkcji napojów',
    division: '28',
    section: 'C',
  },
  {
    code: '28.94.Z',
    name: 'Produkcja maszyn dla przemysłu tekstylnego, odzieżowego i skórzanego',
    division: '28',
    section: 'C',
  },
  {
    code: '28.95.Z',
    name: 'Produkcja maszyn dla przemysłu papierniczego',
    division: '28',
    section: 'C',
  },
  {
    code: '28.96.Z',
    name: 'Produkcja maszyn do obróbki gumy lub tworzyw sztucznych oraz wytwarzania wyrobów z tych materiałów',
    division: '28',
    section: 'C',
  },
  {
    code: '28.99.Z',
    name: 'Produkcja pozostałych maszyn specjalnego przeznaczenia, gdzie indziej niesklasyfikowana',
    division: '28',
    section: 'C',
  },
  {
    code: '29.10.A',
    name: 'Produkcja silników do pojazdów samochodowych (z wyłączeniem motocykli) oraz do ciągników rolniczych',
    division: '29',
    section: 'C',
  },
  { code: '29.10.B', name: 'Produkcja samochodów osobowych', division: '29', section: 'C' },
  { code: '29.10.C', name: 'Produkcja autobusów', division: '29', section: 'C' },
  {
    code: '29.10.D',
    name: 'Produkcja pojazdów samochodowych przeznaczonych do przewozu towarów',
    division: '29',
    section: 'C',
  },
  {
    code: '29.10.E',
    name: 'Produkcja pozostałych pojazdów samochodowych, z wyłączeniem motocykli',
    division: '29',
    section: 'C',
  },
  {
    code: '29.20.Z',
    name: 'Produkcja nadwozi do pojazdów silnikowych; produkcja przyczep i naczep',
    division: '29',
    section: 'C',
  },
  {
    code: '29.31.Z',
    name: 'Produkcja wyposażenia elektrycznego i elektronicznego do pojazdów silnikowych',
    division: '29',
    section: 'C',
  },
  {
    code: '29.32.Z',
    name: 'Produkcja pozostałych części i akcesoriów do pojazdów silnikowych, z wyłączeniem motocykli',
    division: '29',
    section: 'C',
  },
  {
    code: '30.11.Z',
    name: 'Produkcja statków i konstrukcji pływających',
    division: '30',
    section: 'C',
  },
  {
    code: '30.12.Z',
    name: 'Produkcja łodzi wycieczkowych i sportowych',
    division: '30',
    section: 'C',
  },
  {
    code: '30.20.Z',
    name: 'Produkcja lokomotyw kolejowych oraz taboru szynowego',
    division: '30',
    section: 'C',
  },
  {
    code: '30.30.Z',
    name: 'Produkcja statków powietrznych, statków kosmicznych i podobnych maszyn',
    division: '30',
    section: 'C',
  },
  { code: '30.40.Z', name: 'Produkcja wojskowych pojazdów bojowych', division: '30', section: 'C' },
  { code: '30.91.Z', name: 'Produkcja motocykli', division: '30', section: 'C' },
  {
    code: '30.92.Z',
    name: 'Produkcja rowerów i wózków inwalidzkich',
    division: '30',
    section: 'C',
  },
  {
    code: '30.99.Z',
    name: 'Produkcja pozostałego sprzętu transportowego, gdzie indziej niesklasyfikowana',
    division: '30',
    section: 'C',
  },
  { code: '31.01.Z', name: 'Produkcja mebli biurowych i sklepowych', division: '31', section: 'C' },
  { code: '31.02.Z', name: 'Produkcja mebli kuchennych', division: '31', section: 'C' },
  { code: '31.03.Z', name: 'Produkcja materaców', division: '31', section: 'C' },
  { code: '31.09.Z', name: 'Produkcja pozostałych mebli', division: '31', section: 'C' },
  { code: '32.11.Z', name: 'Produkcja monet', division: '32', section: 'C' },
  {
    code: '32.12.Z',
    name: 'Produkcja wyrobów jubilerskich i podobnych',
    division: '32',
    section: 'C',
  },
  {
    code: '32.13.Z',
    name: 'Produkcja sztucznej biżuterii i wyrobów podobnych',
    division: '32',
    section: 'C',
  },
  { code: '32.20.Z', name: 'Produkcja instrumentów muzycznych', division: '32', section: 'C' },
  { code: '32.30.Z', name: 'Produkcja sprzętu sportowego', division: '32', section: 'C' },
  { code: '32.40.Z', name: 'Produkcja gier i zabawek', division: '32', section: 'C' },
  {
    code: '32.50.Z',
    name: 'Produkcja urządzeń, instrumentów oraz wyrobów medycznych, włączając dentystyczne',
    division: '32',
    section: 'C',
  },
  { code: '32.91.Z', name: 'Produkcja mioteł, szczotek i pędzli', division: '32', section: 'C' },
  {
    code: '32.99.Z',
    name: 'Produkcja pozostałych wyrobów, gdzie indziej niesklasyfikowana',
    division: '32',
    section: 'C',
  },
  {
    code: '33.11.Z',
    name: 'Naprawa i konserwacja metalowych wyrobów gotowych',
    division: '33',
    section: 'C',
  },
  { code: '33.12.Z', name: 'Naprawa i konserwacja maszyn', division: '33', section: 'C' },
  {
    code: '33.13.Z',
    name: 'Naprawa i konserwacja urządzeń elektronicznych i optycznych',
    division: '33',
    section: 'C',
  },
  {
    code: '33.14.Z',
    name: 'Naprawa i konserwacja urządzeń elektrycznych',
    division: '33',
    section: 'C',
  },
  { code: '33.15.Z', name: 'Naprawa i konserwacja statków i łodzi', division: '33', section: 'C' },
  {
    code: '33.16.Z',
    name: 'Naprawa i konserwacja statków powietrznych i statków kosmicznych',
    division: '33',
    section: 'C',
  },
  {
    code: '33.17.Z',
    name: 'Naprawa i konserwacja pozostałego sprzętu transportowego',
    division: '33',
    section: 'C',
  },
  {
    code: '33.19.Z',
    name: 'Naprawa i konserwacja pozostałego sprzętu i wyposażenia',
    division: '33',
    section: 'C',
  },
  {
    code: '33.20.Z',
    name: 'Instalowanie maszyn przemysłowych, sprzętu i wyposażenia',
    division: '33',
    section: 'C',
  },
  { code: '35.11.Z', name: 'Wytwarzanie energii elektrycznej', division: '35', section: 'D' },
  { code: '35.12.Z', name: 'Przesyłanie energii elektrycznej', division: '35', section: 'D' },
  { code: '35.13.Z', name: 'Dystrybucja energii elektrycznej', division: '35', section: 'D' },
  { code: '35.14.Z', name: 'Handel energią elektryczną', division: '35', section: 'D' },
  { code: '35.21.Z', name: 'Wytwarzanie paliw gazowych', division: '35', section: 'D' },
  {
    code: '35.22.Z',
    name: 'Dystrybucja paliw gazowych w systemie sieciowym',
    division: '35',
    section: 'D',
  },
  {
    code: '35.23.Z',
    name: 'Handel paliwami gazowymi w systemie sieciowym',
    division: '35',
    section: 'D',
  },
  {
    code: '35.30.Z',
    name: 'Wytwarzanie i zaopatrywanie w parę wodną, gorącą wodę i powietrze do układów klimatyzacyjnych',
    division: '35',
    section: 'D',
  },
  { code: '36.00.Z', name: 'POBÓR, UZDATNIANIE I DOSTARCZANIE WODY', division: '36', section: 'E' },
  { code: '37.00.Z', name: 'ODPROWADZANIE I OCZYSZCZANIE ŚCIEKÓW', division: '37', section: 'E' },
  {
    code: '38.11.Z',
    name: 'Zbieranie odpadów innych niż niebezpieczne',
    division: '38',
    section: 'E',
  },
  { code: '38.12.Z', name: 'Zbieranie odpadów niebezpiecznych', division: '38', section: 'E' },
  {
    code: '38.21.Z',
    name: 'Obróbka i usuwanie odpadów innych niż niebezpieczne',
    division: '38',
    section: 'E',
  },
  {
    code: '38.22.Z',
    name: 'Przetwarzanie i unieszkodliwianie odpadów niebezpiecznych',
    division: '38',
    section: 'E',
  },
  { code: '38.31.Z', name: 'Demontaż wyrobów zużytych', division: '38', section: 'E' },
  {
    code: '38.32.Z',
    name: 'Odzysk surowców z materiałów segregowanych',
    division: '38',
    section: 'E',
  },
  {
    code: '39.00.Z',
    name: 'DZIAŁALNOŚĆ ZWIĄZANA Z REKULTYWACJĄ I POZOSTAŁA DZIAŁALNOŚĆ USŁUGOWA ZWIĄZANA Z GOSPODARKĄ ODPADAMI',
    division: '39',
    section: 'E',
  },
  {
    code: '41.10.Z',
    name: 'Realizacja projektów budowlanych związanych ze wznoszeniem budynków',
    division: '41',
    section: 'F',
  },
  {
    code: '41.20.Z',
    name: 'Roboty budowlane związane ze wznoszeniem budynków mieszkalnych i niemieszkalnych',
    division: '41',
    section: 'F',
  },
  {
    code: '42.11.Z',
    name: 'Roboty związane z budową dróg i autostrad',
    division: '42',
    section: 'F',
  },
  {
    code: '42.12.Z',
    name: 'Roboty związane z budową dróg szynowych i kolei podziemnej',
    division: '42',
    section: 'F',
  },
  {
    code: '42.13.Z',
    name: 'Roboty związane z budową mostów i tuneli',
    division: '42',
    section: 'F',
  },
  {
    code: '42.21.Z',
    name: 'Roboty związane z budową rurociągów przesyłowych i sieci rozdzielczych',
    division: '42',
    section: 'F',
  },
  {
    code: '42.22.Z',
    name: 'Roboty związane z budową linii telekomunikacyjnych i elektroenergetycznych',
    division: '42',
    section: 'F',
  },
  {
    code: '42.91.Z',
    name: 'Roboty związane z budową obiektów inżynierii wodnej',
    division: '42',
    section: 'F',
  },
  {
    code: '42.99.Z',
    name: 'Roboty związane z budową pozostałych obiektów inżynierii lądowej i wodnej, gdzie indziej niesklasyfikowane',
    division: '42',
    section: 'F',
  },
  {
    code: '43.11.Z',
    name: 'Rozbiórka i burzenie obiektów budowlanych',
    division: '43',
    section: 'F',
  },
  { code: '43.12.Z', name: 'Przygotowanie terenu pod budowę', division: '43', section: 'F' },
  {
    code: '43.13.Z',
    name: 'Wykonywanie wykopów i wierceń geologiczno-inżynierskich',
    division: '43',
    section: 'F',
  },
  { code: '43.21.Z', name: 'Wykonywanie instalacji elektrycznych', division: '43', section: 'F' },
  {
    code: '43.22.Z',
    name: 'Wykonywanie instalacji wodno-kanalizacyjnych, cieplnych, gazowych i klimatyzacyjnych',
    division: '43',
    section: 'F',
  },
  {
    code: '43.29.Z',
    name: 'Wykonywanie pozostałych instalacji budowlanych',
    division: '43',
    section: 'F',
  },
  { code: '43.31.Z', name: 'Tynkowanie', division: '43', section: 'F' },
  { code: '43.32.Z', name: 'Zakładanie stolarki budowlanej', division: '43', section: 'F' },
  {
    code: '43.33.Z',
    name: 'Posadzkarstwo; tapetowanie i oblicowywanie ścian',
    division: '43',
    section: 'F',
  },
  { code: '43.34.Z', name: 'Malowanie i szklenie', division: '43', section: 'F' },
  {
    code: '43.39.Z',
    name: 'Wykonywanie pozostałych robót budowlanych wykończeniowych',
    division: '43',
    section: 'F',
  },
  {
    code: '43.91.Z',
    name: 'Wykonywanie konstrukcji i pokryć dachowych',
    division: '43',
    section: 'F',
  },
  {
    code: '43.99.Z',
    name: 'Pozostałe specjalistyczne roboty budowlane, gdzie indziej niesklasyfikowane',
    division: '43',
    section: 'F',
  },
  {
    code: '45.11.Z',
    name: 'Sprzedaż hurtowa i detaliczna samochodów osobowych i furgonetek',
    division: '45',
    section: 'G',
  },
  {
    code: '45.19.Z',
    name: 'Sprzedaż hurtowa i detaliczna pozostałych pojazdów samochodowych, z wyłączeniem motocykli',
    division: '45',
    section: 'G',
  },
  {
    code: '45.20.Z',
    name: 'Konserwacja i naprawa pojazdów samochodowych, z wyłączeniem motocykli',
    division: '45',
    section: 'G',
  },
  {
    code: '45.31.Z',
    name: 'Sprzedaż hurtowa części i akcesoriów do pojazdów samochodowych, z wyłączeniem motocykli',
    division: '45',
    section: 'G',
  },
  {
    code: '45.32.Z',
    name: 'Sprzedaż detaliczna części i akcesoriów do pojazdów samochodowych, z wyłączeniem motocykli',
    division: '45',
    section: 'G',
  },
  {
    code: '45.40.Z',
    name: 'Sprzedaż hurtowa i detaliczna motocykli, ich naprawa i konserwacja oraz sprzedaż hurtowa i detaliczna części i akcesoriów do nich',
    division: '45',
    section: 'G',
  },
  {
    code: '46.11.Z',
    name: 'Działalność agentów zajmujących się sprzedażą płodów rolnych, żywych zwierząt, surowców dla przemysłu tekstylnego i półproduktów',
    division: '46',
    section: 'G',
  },
  {
    code: '46.12.Z',
    name: 'Działalność agentów zajmujących się sprzedażą paliw, rud, metali i chemikaliów przemysłowych',
    division: '46',
    section: 'G',
  },
  {
    code: '46.13.Z',
    name: 'Działalność agentów zajmujących się sprzedażą drewna i materiałów budowlanych',
    division: '46',
    section: 'G',
  },
  {
    code: '46.14.Z',
    name: 'Działalność agentów zajmujących się sprzedażą maszyn, urządzeń przemysłowych, statków i samolotów',
    division: '46',
    section: 'G',
  },
  {
    code: '46.15.Z',
    name: 'Działalność agentów zajmujących się sprzedażą mebli, artykułów gospodarstwa domowego i drobnych wyrobów metalowych',
    division: '46',
    section: 'G',
  },
  {
    code: '46.16.Z',
    name: 'Działalność agentów zajmujących się sprzedażą wyrobów tekstylnych, odzieży, wyrobów futrzarskich, obuwia i artykułów skórzanych',
    division: '46',
    section: 'G',
  },
  {
    code: '46.17.Z',
    name: 'Działalność agentów zajmujących się sprzedażą żywności, napojów i wyrobów tytoniowych',
    division: '46',
    section: 'G',
  },
  {
    code: '46.18.Z',
    name: 'Działalność agentów specjalizujących się w sprzedaży pozostałych określonych towarów',
    division: '46',
    section: 'G',
  },
  {
    code: '46.19.Z',
    name: 'Działalność agentów zajmujących się sprzedażą towarów różnego rodzaju',
    division: '46',
    section: 'G',
  },
  {
    code: '46.21.Z',
    name: 'Sprzedaż hurtowa zboża, nieprzetworzonego tytoniu, nasion i pasz dla zwierząt',
    division: '46',
    section: 'G',
  },
  { code: '46.22.Z', name: 'Sprzedaż hurtowa kwiatów i roślin', division: '46', section: 'G' },
  { code: '46.23.Z', name: 'Sprzedaż hurtowa żywych zwierząt', division: '46', section: 'G' },
  { code: '46.24.Z', name: 'Sprzedaż hurtowa skór', division: '46', section: 'G' },
  { code: '46.31.Z', name: 'Sprzedaż hurtowa owoców i warzyw', division: '46', section: 'G' },
  {
    code: '46.32.Z',
    name: 'Sprzedaż hurtowa mięsa i wyrobów z mięsa',
    division: '46',
    section: 'G',
  },
  {
    code: '46.33.Z',
    name: 'Sprzedaż hurtowa mleka, wyrobów mleczarskich, jaj, olejów i tłuszczów jadalnych',
    division: '46',
    section: 'G',
  },
  { code: '46.34.A', name: 'Sprzedaż hurtowa napojów alkoholowych', division: '46', section: 'G' },
  {
    code: '46.34.B',
    name: 'Sprzedaż hurtowa napojów bezalkoholowych',
    division: '46',
    section: 'G',
  },
  { code: '46.35.Z', name: 'Sprzedaż hurtowa wyrobów tytoniowych', division: '46', section: 'G' },
  {
    code: '46.36.Z',
    name: 'Sprzedaż hurtowa cukru, czekolady, wyrobów cukierniczych i piekarskich',
    division: '46',
    section: 'G',
  },
  {
    code: '46.37.Z',
    name: 'Sprzedaż hurtowa herbaty, kawy, kakao i przypraw',
    division: '46',
    section: 'G',
  },
  {
    code: '46.38.Z',
    name: 'Sprzedaż hurtowa pozostałej żywności, włączając ryby, skorupiaki i mięczaki',
    division: '46',
    section: 'G',
  },
  {
    code: '46.39.Z',
    name: 'Sprzedaż hurtowa niewyspecjalizowana żywności, napojów i wyrobów tytoniowych',
    division: '46',
    section: 'G',
  },
  { code: '46.41.Z', name: 'Sprzedaż hurtowa wyrobów tekstylnych', division: '46', section: 'G' },
  { code: '46.42.Z', name: 'Sprzedaż hurtowa odzieży i obuwia', division: '46', section: 'G' },
  {
    code: '46.43.Z',
    name: 'Sprzedaż hurtowa elektrycznych artykułów użytku domowego',
    division: '46',
    section: 'G',
  },
  {
    code: '46.44.Z',
    name: 'Sprzedaż hurtowa wyrobów porcelanowych, ceramicznych i szklanych oraz środków czyszczących',
    division: '46',
    section: 'G',
  },
  { code: '46.45.Z', name: 'Sprzedaż hurtowa perfum i kosmetyków', division: '46', section: 'G' },
  {
    code: '46.46.Z',
    name: 'Sprzedaż hurtowa wyrobów farmaceutycznych i medycznych',
    division: '46',
    section: 'G',
  },
  {
    code: '46.47.Z',
    name: 'Sprzedaż hurtowa mebli, dywanów i sprzętu oświetleniowego',
    division: '46',
    section: 'G',
  },
  {
    code: '46.48.Z',
    name: 'Sprzedaż hurtowa zegarków, zegarów i biżuterii',
    division: '46',
    section: 'G',
  },
  {
    code: '46.49.Z',
    name: 'Sprzedaż hurtowa pozostałych artykułów użytku domowego',
    division: '46',
    section: 'G',
  },
  {
    code: '46.51.Z',
    name: 'Sprzedaż hurtowa komputerów, urządzeń peryferyjnych i oprogramowania',
    division: '46',
    section: 'G',
  },
  {
    code: '46.52.Z',
    name: 'Sprzedaż hurtowa sprzętu elektronicznego i telekomunikacyjnego oraz części do niego',
    division: '46',
    section: 'G',
  },
  {
    code: '46.61.Z',
    name: 'Sprzedaż hurtowa maszyn i urządzeń rolniczych oraz dodatkowego wyposażenia',
    division: '46',
    section: 'G',
  },
  { code: '46.62.Z', name: 'Sprzedaż hurtowa obrabiarek', division: '46', section: 'G' },
  {
    code: '46.63.Z',
    name: 'Sprzedaż hurtowa maszyn wykorzystywanych w górnictwie, budownictwie oraz inżynierii lądowej i wodnej',
    division: '46',
    section: 'G',
  },
  {
    code: '46.64.Z',
    name: 'Sprzedaż hurtowa maszyn dla przemysłu tekstylnego oraz maszyn do szycia i maszyn dziewiarskich',
    division: '46',
    section: 'G',
  },
  { code: '46.65.Z', name: 'Sprzedaż hurtowa mebli biurowych', division: '46', section: 'G' },
  {
    code: '46.66.Z',
    name: 'Sprzedaż hurtowa pozostałych maszyn i urządzeń biurowych',
    division: '46',
    section: 'G',
  },
  {
    code: '46.69.Z',
    name: 'Sprzedaż hurtowa pozostałych maszyn i urządzeń',
    division: '46',
    section: 'G',
  },
  {
    code: '46.71.Z',
    name: 'Sprzedaż hurtowa paliw i produktów pochodnych',
    division: '46',
    section: 'G',
  },
  { code: '46.72.Z', name: 'Sprzedaż hurtowa metali i rud metali', division: '46', section: 'G' },
  {
    code: '46.73.Z',
    name: 'Sprzedaż hurtowa drewna, materiałów budowlanych i wyposażenia sanitarnego',
    division: '46',
    section: 'G',
  },
  {
    code: '46.74.Z',
    name: 'Sprzedaż hurtowa wyrobów metalowych oraz sprzętu i dodatkowego wyposażenia hydraulicznego i grzejnego',
    division: '46',
    section: 'G',
  },
  { code: '46.75.Z', name: 'Sprzedaż hurtowa wyrobów chemicznych', division: '46', section: 'G' },
  {
    code: '46.76.Z',
    name: 'Sprzedaż hurtowa pozostałych półproduktów',
    division: '46',
    section: 'G',
  },
  { code: '46.77.Z', name: 'Sprzedaż hurtowa odpadów i złomu', division: '46', section: 'G' },
  { code: '46.90.Z', name: 'Sprzedaż hurtowa niewyspecjalizowana', division: '46', section: 'G' },
  {
    code: '47.11.Z',
    name: 'Sprzedaż detaliczna prowadzona w niewyspecjalizowanych sklepach z przewagą żywności, napojów i wyrobów tytoniowych',
    division: '47',
    section: 'G',
  },
  {
    code: '47.19.Z',
    name: 'Pozostała sprzedaż detaliczna prowadzona w niewyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.21.Z',
    name: 'Sprzedaż detaliczna owoców i warzyw prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.22.Z',
    name: 'Sprzedaż detaliczna mięsa i wyrobów z mięsa prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.23.Z',
    name: 'Sprzedaż detaliczna ryb, skorupiaków i mięczaków prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.24.Z',
    name: 'Sprzedaż detaliczna pieczywa, ciast, wyrobów ciastkarskich i cukierniczych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.25.Z',
    name: 'Sprzedaż detaliczna napojów alkoholowych i bezalkoholowych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.26.Z',
    name: 'Sprzedaż detaliczna wyrobów tytoniowych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.29.Z',
    name: 'Sprzedaż detaliczna pozostałej żywności prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.30.Z',
    name: 'Sprzedaż detaliczna paliw do pojazdów silnikowych na stacjach paliw',
    division: '47',
    section: 'G',
  },
  {
    code: '47.41.Z',
    name: 'Sprzedaż detaliczna komputerów, urządzeń peryferyjnych i oprogramowania prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.42.Z',
    name: 'Sprzedaż detaliczna sprzętu telekomunikacyjnego prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.43.Z',
    name: 'Sprzedaż detaliczna sprzętu audiowizualnego prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.51.Z',
    name: 'Sprzedaż detaliczna wyrobów tekstylnych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.52.Z',
    name: 'Sprzedaż detaliczna drobnych wyrobów metalowych, farb i szkła prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.53.Z',
    name: 'Sprzedaż detaliczna dywanów, chodników i innych pokryć podłogowych oraz pokryć ściennych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.54.Z',
    name: 'Sprzedaż detaliczna elektrycznego sprzętu gospodarstwa domowego prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.59.Z',
    name: 'Sprzedaż detaliczna mebli, sprzętu oświetleniowego i pozostałych artykułów użytku domowego prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.61.Z',
    name: 'Sprzedaż detaliczna książek prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.62.Z',
    name: 'Sprzedaż detaliczna gazet i artykułów piśmiennych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.63.Z',
    name: 'Sprzedaż detaliczna nagrań dźwiękowych i audiowizualnych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.64.Z',
    name: 'Sprzedaż detaliczna sprzętu sportowego prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.65.Z',
    name: 'Sprzedaż detaliczna gier i zabawek prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.71.Z',
    name: 'Sprzedaż detaliczna odzieży prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.72.Z',
    name: 'Sprzedaż detaliczna obuwia i wyrobów skórzanych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.73.Z',
    name: 'Sprzedaż detaliczna wyrobów farmaceutycznych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.74.Z',
    name: 'Sprzedaż detaliczna wyrobów medycznych, włączając ortopedyczne, prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.75.Z',
    name: 'Sprzedaż detaliczna kosmetyków i artykułów toaletowych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.76.Z',
    name: 'Sprzedaż detaliczna kwiatów, roślin, nasion, nawozów, żywych zwierząt domowych, karmy dla zwierząt domowych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.77.Z',
    name: 'Sprzedaż detaliczna zegarków, zegarów i biżuterii prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.78.Z',
    name: 'Sprzedaż detaliczna pozostałych nowych wyrobów prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.79.Z',
    name: 'Sprzedaż detaliczna artykułów używanych prowadzona w wyspecjalizowanych sklepach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.81.Z',
    name: 'Sprzedaż detaliczna żywności, napojów i wyrobów tytoniowych prowadzona na straganach i targowiskach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.82.Z',
    name: 'Sprzedaż detaliczna wyrobów tekstylnych, odzieży i obuwia prowadzona na straganach i targowiskach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.89.Z',
    name: 'Sprzedaż detaliczna pozostałych wyrobów prowadzona na straganach i targowiskach',
    division: '47',
    section: 'G',
  },
  {
    code: '47.91.Z',
    name: 'Sprzedaż detaliczna prowadzona przez domy sprzedaży wysyłkowej lub Internet',
    division: '47',
    section: 'G',
  },
  {
    code: '47.99.Z',
    name: 'Pozostała sprzedaż detaliczna prowadzona poza siecią sklepową, straganami i targowiskami',
    division: '47',
    section: 'G',
  },
  {
    code: '49.10.Z',
    name: 'Transport kolejowy pasażerski międzymiastowy',
    division: '49',
    section: 'H',
  },
  { code: '49.20.Z', name: 'Transport kolejowy towarów', division: '49', section: 'H' },
  {
    code: '49.31.Z',
    name: 'Transport lądowy pasażerski, miejski i podmiejski',
    division: '49',
    section: 'H',
  },
  { code: '49.32.Z', name: 'Działalność taksówek osobowych', division: '49', section: 'H' },
  {
    code: '49.39.Z',
    name: 'Pozostały transport lądowy pasażerski, gdzie indziej niesklasyfikowany',
    division: '49',
    section: 'H',
  },
  { code: '49.41.Z', name: 'Transport drogowy towarów', division: '49', section: 'H' },
  {
    code: '49.42.Z',
    name: 'Działalność usługowa związana z przeprowadzkami',
    division: '49',
    section: 'H',
  },
  { code: '49.50.A', name: 'Transport rurociągami paliw gazowych', division: '49', section: 'H' },
  {
    code: '49.50.B',
    name: 'Transport rurociągowy pozostałych towarów',
    division: '49',
    section: 'H',
  },
  {
    code: '50.10.Z',
    name: 'Transport morski i przybrzeżny pasażerski',
    division: '50',
    section: 'H',
  },
  { code: '50.20.Z', name: 'Transport morski i przybrzeżny towarów', division: '50', section: 'H' },
  { code: '50.30.Z', name: 'Transport wodny śródlądowy pasażerski', division: '50', section: 'H' },
  { code: '50.40.Z', name: 'Transport wodny śródlądowy towarów', division: '50', section: 'H' },
  { code: '51.10.Z', name: 'Transport lotniczy pasażerski', division: '51', section: 'H' },
  { code: '51.21.Z', name: 'Transport lotniczy towarów', division: '51', section: 'H' },
  { code: '51.22.Z', name: 'Transport kosmiczny', division: '51', section: 'H' },
  {
    code: '52.10.A',
    name: 'Magazynowanie i przechowywanie paliw gazowych',
    division: '52',
    section: 'H',
  },
  {
    code: '52.10.B',
    name: 'Magazynowanie i przechowywanie pozostałych towarów',
    division: '52',
    section: 'H',
  },
  {
    code: '52.21.Z',
    name: 'Działalność usługowa wspomagająca transport lądowy',
    division: '52',
    section: 'H',
  },
  {
    code: '52.22.A',
    name: 'Działalność usługowa wspomagająca transport morski',
    division: '52',
    section: 'H',
  },
  {
    code: '52.22.B',
    name: 'Działalność usługowa wspomagająca transport śródlądowy',
    division: '52',
    section: 'H',
  },
  {
    code: '52.23.Z',
    name: 'Działalność usługowa wspomagająca transport lotniczy',
    division: '52',
    section: 'H',
  },
  { code: '52.24.A', name: 'Przeładunek towarów w portach morskich', division: '52', section: 'H' },
  {
    code: '52.24.B',
    name: 'Przeładunek towarów w portach śródlądowych',
    division: '52',
    section: 'H',
  },
  {
    code: '52.24.C',
    name: 'Przeładunek towarów w pozostałych punktach przeładunkowych',
    division: '52',
    section: 'H',
  },
  {
    code: '52.29.A',
    name: 'Działalność morskich agencji transportowych',
    division: '52',
    section: 'H',
  },
  {
    code: '52.29.B',
    name: 'Działalność śródlądowych agencji transportowych',
    division: '52',
    section: 'H',
  },
  {
    code: '52.29.C',
    name: 'Działalność pozostałych agencji transportowych',
    division: '52',
    section: 'H',
  },
  {
    code: '53.10.Z',
    name: 'Działalność pocztowa objęta obowiązkiem świadczenia usług powszechnych (operatora publicznego)',
    division: '53',
    section: 'H',
  },
  {
    code: '53.20.Z',
    name: 'Pozostała działalność pocztowa i kurierska',
    division: '53',
    section: 'H',
  },
  {
    code: '55.10.Z',
    name: 'Hotele i podobne obiekty zakwaterowania',
    division: '55',
    section: 'I',
  },
  {
    code: '55.20.Z',
    name: 'Obiekty noclegowe turystyczne i miejsca krótkotrwałego zakwaterowania',
    division: '55',
    section: 'I',
  },
  {
    code: '55.30.Z',
    name: 'Pola kempingowe (włączając pola dla pojazdów kempingowych) i pola namiotowe',
    division: '55',
    section: 'I',
  },
  { code: '55.90.Z', name: 'Pozostałe zakwaterowanie', division: '55', section: 'I' },
  {
    code: '56.10.A',
    name: 'Restauracje i inne stałe placówki gastronomiczne',
    division: '56',
    section: 'I',
  },
  { code: '56.10.B', name: 'Ruchome placówki gastronomiczne', division: '56', section: 'I' },
  {
    code: '56.21.Z',
    name: 'Przygotowywanie i dostarczanie żywności dla odbiorców zewnętrznych (katering)',
    division: '56',
    section: 'I',
  },
  {
    code: '56.29.Z',
    name: 'Pozostała usługowa działalność gastronomiczna',
    division: '56',
    section: 'I',
  },
  { code: '56.30.Z', name: 'Przygotowywanie i podawanie napojów', division: '56', section: 'I' },
  { code: '58.11.Z', name: 'Wydawanie książek', division: '58', section: 'J' },
  {
    code: '58.12.Z',
    name: 'Wydawanie wykazów oraz list (np. adresowych, telefonicznych)',
    division: '58',
    section: 'J',
  },
  { code: '58.13.Z', name: 'Wydawanie gazet', division: '58', section: 'J' },
  {
    code: '58.14.Z',
    name: 'Wydawanie czasopism i pozostałych periodyków',
    division: '58',
    section: 'J',
  },
  { code: '58.19.Z', name: 'Pozostała działalność wydawnicza', division: '58', section: 'J' },
  {
    code: '58.21.Z',
    name: 'Działalność wydawnicza w zakresie gier komputerowych',
    division: '58',
    section: 'J',
  },
  {
    code: '58.29.Z',
    name: 'Działalność wydawnicza w zakresie pozostałego oprogramowania',
    division: '58',
    section: 'J',
  },
  {
    code: '59.11.Z',
    name: 'Działalność związana z produkcją filmów, nagrań wideo i programów telewizyjnych',
    division: '59',
    section: 'J',
  },
  {
    code: '59.12.Z',
    name: 'Działalność postprodukcyjna związana z filmami, nagraniami wideo i programami telewizyjnymi',
    division: '59',
    section: 'J',
  },
  {
    code: '59.13.Z',
    name: 'Działalność związana z dystrybucją filmów, nagrań wideo i programów telewizyjnych',
    division: '59',
    section: 'J',
  },
  {
    code: '59.14.Z',
    name: 'Działalność związana z projekcją filmów',
    division: '59',
    section: 'J',
  },
  {
    code: '59.20.Z',
    name: 'Działalność w zakresie nagrań dźwiękowych i muzycznych',
    division: '59',
    section: 'J',
  },
  { code: '60.10.Z', name: 'Nadawanie programów radiofonicznych', division: '60', section: 'J' },
  {
    code: '60.20.Z',
    name: 'Nadawanie programów telewizyjnych ogólnodostępnych i abonamentowych',
    division: '60',
    section: 'J',
  },
  {
    code: '61.10.Z',
    name: 'Działalność w zakresie telekomunikacji przewodowej',
    division: '61',
    section: 'J',
  },
  {
    code: '61.20.Z',
    name: 'Działalność w zakresie telekomunikacji bezprzewodowej, z wyłączeniem telekomunikacji satelitarnej',
    division: '61',
    section: 'J',
  },
  {
    code: '61.30.Z',
    name: 'Działalność w zakresie telekomunikacji satelitarnej',
    division: '61',
    section: 'J',
  },
  {
    code: '61.90.Z',
    name: 'Działalność w zakresie pozostałej telekomunikacji',
    division: '61',
    section: 'J',
  },
  { code: '62.01.Z', name: 'Działalność związana z oprogramowaniem', division: '62', section: 'J' },
  {
    code: '62.02.Z',
    name: 'Działalność związana z doradztwem w zakresie informatyki',
    division: '62',
    section: 'J',
  },
  {
    code: '62.03.Z',
    name: 'Działalność związana z zarządzaniem urządzeniami informatycznymi',
    division: '62',
    section: 'J',
  },
  {
    code: '62.09.Z',
    name: 'Pozostała działalność usługowa w zakresie technologii informatycznych i komputerowych',
    division: '62',
    section: 'J',
  },
  {
    code: '63.11.Z',
    name: 'Przetwarzanie danych; zarządzanie stronami internetowymi (hosting) i podobna działalność',
    division: '63',
    section: 'J',
  },
  { code: '63.12.Z', name: 'Działalność portali internetowych', division: '63', section: 'J' },
  { code: '63.91.Z', name: 'Działalność agencji informacyjnych', division: '63', section: 'J' },
  {
    code: '63.99.Z',
    name: 'Pozostała działalność usługowa w zakresie informacji, gdzie indziej niesklasyfikowana',
    division: '63',
    section: 'J',
  },
  { code: '64.11.Z', name: 'Działalność banku centralnego', division: '64', section: 'K' },
  { code: '64.19.Z', name: 'Pozostałe pośrednictwo pieniężne', division: '64', section: 'K' },
  { code: '64.20.Z', name: 'Działalność holdingów finansowych', division: '64', section: 'K' },
  {
    code: '64.30.Z',
    name: 'Działalność trustów, funduszów i podobnych instytucji finansowych',
    division: '64',
    section: 'K',
  },
  { code: '64.91.Z', name: 'Leasing finansowy', division: '64', section: 'K' },
  { code: '64.92.Z', name: 'Pozostałe formy udzielania kredytów', division: '64', section: 'K' },
  {
    code: '64.99.Z',
    name: 'Pozostała finansowa działalność usługowa, gdzie indziej niesklasyfikowana, z wyłączeniem ubezpieczeń i funduszów emerytalnych',
    division: '64',
    section: 'K',
  },
  { code: '65.11.Z', name: 'Ubezpieczenia na życie', division: '65', section: 'K' },
  {
    code: '65.12.Z',
    name: 'Pozostałe ubezpieczenia osobowe oraz ubezpieczenia majątkowe',
    division: '65',
    section: 'K',
  },
  { code: '65.20.Z', name: 'Reasekuracja', division: '65', section: 'K' },
  { code: '65.30.Z', name: 'Fundusze emerytalne', division: '65', section: 'K' },
  { code: '66.11.Z', name: 'Zarządzanie rynkami finansowymi', division: '66', section: 'K' },
  {
    code: '66.12.Z',
    name: 'Działalność maklerska związana z rynkiem papierów wartościowych i towarów giełdowych',
    division: '66',
    section: 'K',
  },
  {
    code: '66.19.Z',
    name: 'Pozostała działalność wspomagająca usługi finansowe, z wyłączeniem ubezpieczeń i funduszów emerytalnych',
    division: '66',
    section: 'K',
  },
  {
    code: '66.21.Z',
    name: 'Działalność związana z oceną ryzyka i szacowaniem poniesionych strat',
    division: '66',
    section: 'K',
  },
  {
    code: '66.22.Z',
    name: 'Działalność agentów i brokerów ubezpieczeniowych',
    division: '66',
    section: 'K',
  },
  {
    code: '66.29.Z',
    name: 'Pozostała działalność wspomagająca ubezpieczenia i fundusze emerytalne',
    division: '66',
    section: 'K',
  },
  {
    code: '66.30.Z',
    name: 'Działalność związana z zarządzaniem funduszami',
    division: '66',
    section: 'K',
  },
  {
    code: '68.10.Z',
    name: 'Kupno i sprzedaż nieruchomości na własny rachunek',
    division: '68',
    section: 'L',
  },
  {
    code: '68.20.Z',
    name: 'Wynajem i zarządzanie nieruchomościami własnymi lub dzierżawionymi',
    division: '68',
    section: 'L',
  },
  {
    code: '68.31.Z',
    name: 'Pośrednictwo w obrocie nieruchomościami',
    division: '68',
    section: 'L',
  },
  {
    code: '68.32.Z',
    name: 'Zarządzanie nieruchomościami wykonywane na zlecenie',
    division: '68',
    section: 'L',
  },
  { code: '69.10.Z', name: 'Działalność prawnicza', division: '69', section: 'M' },
  {
    code: '69.20.Z',
    name: 'Działalność rachunkowo-księgowa; doradztwo podatkowe',
    division: '69',
    section: 'M',
  },
  {
    code: '70.10.Z',
    name: 'Działalność firm centralnych (head offices) i holdingów, z wyłączeniem holdingów finansowych',
    division: '70',
    section: 'M',
  },
  {
    code: '70.21.Z',
    name: 'Stosunki międzyludzkie (public relations) i komunikacja',
    division: '70',
    section: 'M',
  },
  {
    code: '70.22.Z',
    name: 'Pozostałe doradztwo w zakresie prowadzenia działalności gospodarczej i zarządzania',
    division: '70',
    section: 'M',
  },
  { code: '71.11.Z', name: 'Działalność w zakresie architektury', division: '71', section: 'M' },
  {
    code: '71.12.Z',
    name: 'Działalność w zakresie inżynierii i związane z nią doradztwo techniczne',
    division: '71',
    section: 'M',
  },
  {
    code: '71.20.A',
    name: 'Badania i analizy związane z jakością żywności',
    division: '71',
    section: 'M',
  },
  { code: '71.20.B', name: 'Pozostałe badania i analizy techniczne', division: '71', section: 'M' },
  {
    code: '72.11.Z',
    name: 'Badania naukowe i prace rozwojowe w dziedzinie biotechnologii',
    division: '72',
    section: 'M',
  },
  {
    code: '72.19.Z',
    name: 'Badania naukowe i prace rozwojowe w dziedzinie pozostałych nauk przyrodniczych i technicznych',
    division: '72',
    section: 'M',
  },
  {
    code: '72.20.Z',
    name: 'Badania naukowe i prace rozwojowe w dziedzinie nauk społecznych i humanistycznych',
    division: '72',
    section: 'M',
  },
  { code: '73.11.Z', name: 'Działalność agencji reklamowych', division: '73', section: 'M' },
  {
    code: '73.12.A',
    name: 'Pośrednictwo w sprzedaży czasu i miejsca na cele reklamowe w radio i telewizji',
    division: '73',
    section: 'M',
  },
  {
    code: '73.12.B',
    name: 'Pośrednictwo w sprzedaży miejsca na cele reklamowe w mediach drukowanych',
    division: '73',
    section: 'M',
  },
  {
    code: '73.12.C',
    name: 'Pośrednictwo w sprzedaży miejsca na cele reklamowe w mediach elektronicznych (Internet)',
    division: '73',
    section: 'M',
  },
  {
    code: '73.12.D',
    name: 'Pośrednictwo w sprzedaży miejsca na cele reklamowe w pozostałych mediach',
    division: '73',
    section: 'M',
  },
  { code: '73.20.Z', name: 'Badanie rynku i opinii publicznej', division: '73', section: 'M' },
  {
    code: '74.10.Z',
    name: 'Działalność w zakresie specjalistycznego projektowania',
    division: '74',
    section: 'M',
  },
  { code: '74.20.Z', name: 'Działalność fotograficzna', division: '74', section: 'M' },
  { code: '74.30.Z', name: 'Działalność związana z tłumaczeniami', division: '74', section: 'M' },
  {
    code: '74.90.Z',
    name: 'Pozostała działalność profesjonalna, naukowa i techniczna, gdzie indziej niesklasyfikowana',
    division: '74',
    section: 'M',
  },
  { code: '75.00.Z', name: 'DZIAŁALNOŚĆ WETERYNARYJNA', division: '75', section: 'M' },
  {
    code: '77.11.Z',
    name: 'Wynajem i dzierżawa samochodów osobowych i furgonetek',
    division: '77',
    section: 'N',
  },
  {
    code: '77.12.Z',
    name: 'Wynajem i dzierżawa pozostałych pojazdów samochodowych, z wyłączeniem motocykli',
    division: '77',
    section: 'N',
  },
  {
    code: '77.21.Z',
    name: 'Wypożyczanie i dzierżawa sprzętu rekreacyjnego i sportowego',
    division: '77',
    section: 'N',
  },
  {
    code: '77.22.Z',
    name: 'Wypożyczanie kaset wideo, płyt CD, DVD itp.',
    division: '77',
    section: 'N',
  },
  {
    code: '77.29.Z',
    name: 'Wypożyczanie i dzierżawa pozostałych artykułów użytku osobistego i domowego',
    division: '77',
    section: 'N',
  },
  {
    code: '77.31.Z',
    name: 'Wynajem i dzierżawa maszyn i urządzeń rolniczych',
    division: '77',
    section: 'N',
  },
  {
    code: '77.32.Z',
    name: 'Wynajem i dzierżawa maszyn i urządzeń budowlanych',
    division: '77',
    section: 'N',
  },
  {
    code: '77.33.Z',
    name: 'Wynajem i dzierżawa maszyn i urządzeń biurowych, włączając komputery',
    division: '77',
    section: 'N',
  },
  {
    code: '77.34.Z',
    name: 'Wynajem i dzierżawa środków transportu wodnego',
    division: '77',
    section: 'N',
  },
  {
    code: '77.35.Z',
    name: 'Wynajem i dzierżawa środków transportu lotniczego',
    division: '77',
    section: 'N',
  },
  {
    code: '77.39.Z',
    name: 'Wynajem i dzierżawa pozostałych maszyn, urządzeń oraz dóbr materialnych, gdzie indziej niesklasyfikowane',
    division: '77',
    section: 'N',
  },
  {
    code: '77.40.Z',
    name: 'Dzierżawa własności intelektualnej i podobnych produktów, z wyłączeniem prac chronionych prawem autorskim',
    division: '77',
    section: 'N',
  },
  {
    code: '78.10.Z',
    name: 'Działalność związana z wyszukiwaniem miejsc pracy i pozyskiwaniem pracowników',
    division: '78',
    section: 'N',
  },
  { code: '78.20.Z', name: 'Działalność agencji pracy tymczasowej', division: '78', section: 'N' },
  {
    code: '78.30.Z',
    name: 'Pozostała działalność związana z udostępnianiem pracowników',
    division: '78',
    section: 'N',
  },
  { code: '79.11.A', name: 'Działalność agentów turystycznych', division: '79', section: 'N' },
  { code: '79.11.B', name: 'Działalność pośredników turystycznych', division: '79', section: 'N' },
  { code: '79.12.Z', name: 'Działalność organizatorów turystyki', division: '79', section: 'N' },
  {
    code: '79.90.A',
    name: 'Działalność pilotów wycieczek i przewodników turystycznych',
    division: '79',
    section: 'N',
  },
  {
    code: '79.90.B',
    name: 'Działalność w zakresie informacji turystycznej',
    division: '79',
    section: 'N',
  },
  {
    code: '79.90.C',
    name: 'Pozostała działalność usługowa w zakresie rezerwacji, gdzie indziej niesklasyfikowana',
    division: '79',
    section: 'N',
  },
  {
    code: '80.10.Z',
    name: 'Działalność ochroniarska, z wyłączeniem obsługi systemów bezpieczeństwa',
    division: '80',
    section: 'N',
  },
  {
    code: '80.20.Z',
    name: 'Działalność ochroniarska w zakresie obsługi systemów bezpieczeństwa',
    division: '80',
    section: 'N',
  },
  { code: '80.30.Z', name: 'Działalność detektywistyczna', division: '80', section: 'N' },
  {
    code: '81.10.Z',
    name: 'Działalność pomocnicza związana z utrzymaniem porządku w budynkach',
    division: '81',
    section: 'N',
  },
  {
    code: '81.21.Z',
    name: 'Niespecjalistyczne sprzątanie budynków i obiektów przemysłowych',
    division: '81',
    section: 'N',
  },
  {
    code: '81.22.Z',
    name: 'Specjalistyczne sprzątanie budynków i obiektów przemysłowych',
    division: '81',
    section: 'N',
  },
  { code: '81.29.Z', name: 'Pozostałe sprzątanie', division: '81', section: 'N' },
  {
    code: '81.30.Z',
    name: 'Działalność usługowa związana z zagospodarowaniem terenów zieleni',
    division: '81',
    section: 'N',
  },
  {
    code: '82.11.Z',
    name: 'Działalność usługowa związana z administracyjną obsługą biura',
    division: '82',
    section: 'N',
  },
  {
    code: '82.19.Z',
    name: 'Wykonywanie fotokopii, przygotowywanie dokumentów i pozostała specjalistyczna działalność wspomagająca prowadzenie biura',
    division: '82',
    section: 'N',
  },
  {
    code: '82.20.Z',
    name: 'Działalność centrów telefonicznych (call center)',
    division: '82',
    section: 'N',
  },
  {
    code: '82.30.Z',
    name: 'Działalność związana z organizacją targów, wystaw i kongresów',
    division: '82',
    section: 'N',
  },
  {
    code: '82.91.Z',
    name: 'Działalność świadczona przez agencje inkasa i biura kredytowe',
    division: '82',
    section: 'N',
  },
  { code: '82.92.Z', name: 'Działalność związana z pakowaniem', division: '82', section: 'N' },
  {
    code: '82.99.Z',
    name: 'Pozostała działalność wspomagająca prowadzenie działalności gospodarczej, gdzie indziej niesklasyfikowana',
    division: '82',
    section: 'N',
  },
  {
    code: '84.11.Z',
    name: 'Kierowanie podstawowymi rodzajami działalności publicznej',
    division: '84',
    section: 'O',
  },
  {
    code: '84.12.Z',
    name: 'Kierowanie w zakresie działalności związanej z ochroną zdrowia, edukacją, kulturą oraz pozostałymi usługami społecznymi, z wyłączeniem zabezpieczeń społecznych',
    division: '84',
    section: 'O',
  },
  {
    code: '84.13.Z',
    name: 'Kierowanie w zakresie efektywności gospodarowania',
    division: '84',
    section: 'O',
  },
  { code: '84.21.Z', name: 'Sprawy zagraniczne', division: '84', section: 'O' },
  { code: '84.22.Z', name: 'Obrona narodowa', division: '84', section: 'O' },
  { code: '84.23.Z', name: 'Wymiar sprawiedliwości', division: '84', section: 'O' },
  {
    code: '84.24.Z',
    name: 'Bezpieczeństwo państwa, porządek i bezpieczeństwo publiczne',
    division: '84',
    section: 'O',
  },
  { code: '84.25.Z', name: 'Ochrona przeciwpożarowa', division: '84', section: 'O' },
  { code: '84.30.Z', name: 'Obowiązkowe zabezpieczenia społeczne', division: '84', section: 'O' },
  { code: '85.10.Z', name: 'Placówki wychowania przedszkolnego', division: '85', section: 'P' },
  { code: '85.20.Z', name: 'Szkoły podstawowe', division: '85', section: 'P' },
  { code: '85.31.A', name: 'Gimnazja', division: '85', section: 'P' },
  { code: '85.31.B', name: 'Licea ogólnokształcące', division: '85', section: 'P' },
  { code: '85.32.A', name: 'Technika', division: '85', section: 'P' },
  { code: '85.32.B', name: 'Branżowe szkoły I stopnia', division: '85', section: 'P' },
  {
    code: '85.32.C',
    name: 'Szkoły specjalne przysposabiające do pracy',
    division: '85',
    section: 'P',
  },
  { code: '85.32.D', name: 'Branżowe szkoły II stopnia', division: '85', section: 'P' },
  { code: '85.41.A', name: 'Szkoły policealne', division: '85', section: 'P' },
  { code: '85.41.B', name: 'Kolegia pracowników służb społecznych', division: '85', section: 'P' },
  { code: '85.41.C', name: 'Placówki doskonalenia nauczycieli', division: '85', section: 'P' },
  {
    code: '85.42.A',
    name: 'Zakłady kształcenia nauczycieli i kolegia pracowników służb społecznych',
    division: '85',
    section: 'P',
  },
  { code: '85.42.Z', name: 'Szkoły wyższe', division: '85', section: 'P' },
  {
    code: '85.51.Z',
    name: 'Pozaszkolne formy edukacji sportowej oraz zajęć sportowych i rekreacyjnych',
    division: '85',
    section: 'P',
  },
  {
    code: '85.52.Z',
    name: 'Pozaszkolne formy edukacji artystycznej',
    division: '85',
    section: 'P',
  },
  {
    code: '85.53.Z',
    name: 'Pozaszkolne formy edukacji z zakresu nauki jazdy i pilotażu',
    division: '85',
    section: 'P',
  },
  { code: '85.59.A', name: 'Nauka języków obcych', division: '85', section: 'P' },
  {
    code: '85.59.B',
    name: 'Pozostałe pozaszkolne formy edukacji, gdzie indziej niesklasyfikowane',
    division: '85',
    section: 'P',
  },
  { code: '85.60.Z', name: 'Działalność wspomagająca edukację', division: '85', section: 'P' },
  { code: '86.10.Z', name: 'Działalność szpitali', division: '86', section: 'Q' },
  { code: '86.21.Z', name: 'Praktyka lekarska ogólna', division: '86', section: 'Q' },
  { code: '86.22.Z', name: 'Praktyka lekarska specjalistyczna', division: '86', section: 'Q' },
  { code: '86.23.Z', name: 'Praktyka lekarska dentystyczna', division: '86', section: 'Q' },
  { code: '86.90.A', name: 'Działalność fizjoterapeutyczna', division: '86', section: 'Q' },
  { code: '86.90.B', name: 'Działalność pogotowia ratunkowego', division: '86', section: 'Q' },
  { code: '86.90.C', name: 'Praktyka pielęgniarek i położnych', division: '86', section: 'Q' },
  { code: '86.90.D', name: 'Działalność paramedyczna', division: '86', section: 'Q' },
  {
    code: '86.90.E',
    name: 'Pozostała działalność w zakresie opieki zdrowotnej, gdzie indziej niesklasyfikowana',
    division: '86',
    section: 'Q',
  },
  {
    code: '87.10.Z',
    name: 'Pomoc społeczna z zakwaterowaniem zapewniająca opiekę pielęgniarską',
    division: '87',
    section: 'Q',
  },
  {
    code: '87.20.Z',
    name: 'Pomoc społeczna z zakwaterowaniem dla osób z zaburzeniami psychicznymi',
    division: '87',
    section: 'Q',
  },
  {
    code: '87.30.Z',
    name: 'Pomoc społeczna z zakwaterowaniem dla osób w podeszłym wieku i osób niepełnosprawnych',
    division: '87',
    section: 'Q',
  },
  {
    code: '87.90.Z',
    name: 'Pozostała pomoc społeczna z zakwaterowaniem',
    division: '87',
    section: 'Q',
  },
  {
    code: '88.10.Z',
    name: 'Pomoc społeczna bez zakwaterowania dla osób w podeszłym wieku i osób niepełnosprawnych',
    division: '88',
    section: 'Q',
  },
  { code: '88.91.Z', name: 'Opieka dzienna nad dziećmi', division: '88', section: 'Q' },
  {
    code: '88.99.Z',
    name: 'Pozostała pomoc społeczna bez zakwaterowania, gdzie indziej niesklasyfikowana',
    division: '88',
    section: 'Q',
  },
  {
    code: '90.01.Z',
    name: 'Działalność związana z wystawianiem przedstawień artystycznych',
    division: '90',
    section: 'R',
  },
  {
    code: '90.02.Z',
    name: 'Działalność wspomagająca wystawianie przedstawień artystycznych',
    division: '90',
    section: 'R',
  },
  {
    code: '90.03.Z',
    name: 'Artystyczna i literacka działalność twórcza',
    division: '90',
    section: 'R',
  },
  { code: '90.04.Z', name: 'Działalność obiektów kulturalnych', division: '90', section: 'R' },
  { code: '91.01.A', name: 'Działalność bibliotek', division: '91', section: 'R' },
  { code: '91.01.B', name: 'Działalność archiwów', division: '91', section: 'R' },
  { code: '91.02.Z', name: 'Działalność muzeów', division: '91', section: 'R' },
  {
    code: '91.03.Z',
    name: 'Działalność historycznych miejsc i budynków oraz podobnych atrakcji turystycznych',
    division: '91',
    section: 'R',
  },
  {
    code: '91.04.Z',
    name: 'Działalność ogrodów botanicznych i zoologicznych oraz obszarów i obiektów ochrony przyrody',
    division: '91',
    section: 'R',
  },
  {
    code: '92.00.Z',
    name: 'DZIAŁALNOŚĆ ZWIĄZANA Z GRAMI LOSOWYMI I ZAKŁADAMI WZAJEMNYMI',
    division: '92',
    section: 'R',
  },
  { code: '93.11.Z', name: 'Działalność obiektów sportowych', division: '93', section: 'R' },
  { code: '93.12.Z', name: 'Działalność klubów sportowych', division: '93', section: 'R' },
  {
    code: '93.13.Z',
    name: 'Działalność obiektów służących poprawie kondycji fizycznej',
    division: '93',
    section: 'R',
  },
  {
    code: '93.19.Z',
    name: 'Pozostała działalność związana ze sportem',
    division: '93',
    section: 'R',
  },
  {
    code: '93.21.Z',
    name: 'Działalność wesołych miasteczek i parków rozrywki',
    division: '93',
    section: 'R',
  },
  {
    code: '93.29.A',
    name: 'Działalność pokojów zagadek, domów strachu, miejsc do tańczenia i w zakresie innych form rozrywki lub rekreacji organizowanych w pomieszczeniach lub w innych miejscach o zamkniętej przestrzeni',
    division: '93',
    section: 'R',
  },
  {
    code: '93.29.B',
    name: 'Pozostała działalność rozrywkowa i rekreacyjna, gdzie indziej niesklasyfikowana',
    division: '93',
    section: 'R',
  },
  {
    code: '94.11.Z',
    name: 'Działalność organizacji komercyjnych i pracodawców',
    division: '94',
    section: 'S',
  },
  {
    code: '94.12.Z',
    name: 'Działalność organizacji profesjonalnych',
    division: '94',
    section: 'S',
  },
  { code: '94.20.Z', name: 'Działalność związków zawodowych', division: '94', section: 'S' },
  { code: '94.91.Z', name: 'Działalność organizacji religijnych', division: '94', section: 'S' },
  { code: '94.92.Z', name: 'Działalność organizacji politycznych', division: '94', section: 'S' },
  {
    code: '94.99.Z',
    name: 'Działalność pozostałych organizacji członkowskich, gdzie indziej niesklasyfikowana',
    division: '94',
    section: 'S',
  },
  {
    code: '95.11.Z',
    name: 'Naprawa i konserwacja komputerów i urządzeń peryferyjnych',
    division: '95',
    section: 'S',
  },
  {
    code: '95.12.Z',
    name: 'Naprawa i konserwacja sprzętu (tele)komunikacyjnego',
    division: '95',
    section: 'S',
  },
  {
    code: '95.21.Z',
    name: 'Naprawa i konserwacja elektronicznego sprzętu powszechnego użytku',
    division: '95',
    section: 'S',
  },
  {
    code: '95.22.Z',
    name: 'Naprawa i konserwacja urządzeń gospodarstwa domowego oraz sprzętu użytku domowego i ogrodniczego',
    division: '95',
    section: 'S',
  },
  { code: '95.23.Z', name: 'Naprawa obuwia i wyrobów skórzanych', division: '95', section: 'S' },
  {
    code: '95.24.Z',
    name: 'Naprawa i konserwacja mebli i wyposażenia domowego',
    division: '95',
    section: 'S',
  },
  {
    code: '95.25.Z',
    name: 'Naprawa zegarów, zegarków oraz biżuterii',
    division: '95',
    section: 'S',
  },
  {
    code: '95.29.Z',
    name: 'Naprawa pozostałych artykułów użytku osobistego i domowego',
    division: '95',
    section: 'S',
  },
  {
    code: '96.01.Z',
    name: 'Pranie i czyszczenie wyrobów włókienniczych i futrzarskich',
    division: '96',
    section: 'S',
  },
  {
    code: '96.02.Z',
    name: 'Fryzjerstwo i pozostałe zabiegi kosmetyczne',
    division: '96',
    section: 'S',
  },
  { code: '96.03.Z', name: 'Pogrzeby i działalność pokrewna', division: '96', section: 'S' },
  {
    code: '96.04.Z',
    name: 'Działalność usługowa związana z poprawą kondycji fizycznej',
    division: '96',
    section: 'S',
  },
  {
    code: '96.09.Z',
    name: 'Pozostała działalność usługowa, gdzie indziej niesklasyfikowana',
    division: '96',
    section: 'S',
  },
  {
    code: '97.00.Z',
    name: 'GOSPODARSTWA DOMOWE ZATRUDNIAJĄCE PRACOWNIKÓW',
    division: '97',
    section: 'T',
  },
  {
    code: '98.10.Z',
    name: 'Gospodarstwa domowe produkujące wyroby na własne potrzeby',
    division: '98',
    section: 'T',
  },
  {
    code: '98.20.Z',
    name: 'Gospodarstwa domowe świadczące usługi na własne potrzeby',
    division: '98',
    section: 'T',
  },
  { code: '99.00.Z', name: 'ORGANIZACJE I ZESPOŁY EKSTERYTORIALNE', division: '99', section: 'U' },
];
