/**
 * PKD 2025 - Polska Klasyfikacja Działalności
 * Pełna lista 657 kodów PKD na poziomie klasy (format: XX.XX.X)
 */

// PKD Section Labels for grouping in UI
export const PKD_SECTIONS = {
  A: 'A - Rolnictwo, leśnictwo, łowiectwo i rybactwo',
  B: 'B - Górnictwo i wydobywanie',
  C: 'C - Przetwórstwo przemysłowe',
  D: 'D - Wytwarzanie i zaopatrywanie w energię elektryczną, gaz, parę wodną, gorącą wodę i powietrze do układów klimatyzacyjnych',
  E: 'E - Dostawa wody; gospodarowanie ściekami i odpadami oraz działalność związana z rekultywacją',
  F: 'F - Budownictwo',
  G: 'G - Handel hurtowy i detaliczny; naprawa pojazdów samochodowych, włączając motocykle',
  H: 'H - Transport i gospodarka magazynowa',
  I: 'I - Działalność związana z zakwaterowaniem i usługami gastronomicznymi',
  J: 'J - Informacja i komunikacja',
  K: 'K - Działalność finansowa i ubezpieczeniowa',
  L: 'L - Działalność związana z obsługą rynku nieruchomości',
  M: 'M - Działalność profesjonalna, naukowa i techniczna',
  N: 'N - Działalność w zakresie usług administrowania i działalność wspierająca',
  O: 'O - Administracja publiczna i obrona narodowa; obowiązkowe zabezpieczenia społeczne',
  P: 'P - Edukacja',
  Q: 'Q - Opieka zdrowotna i pomoc społeczna',
  R: 'R - Działalność związana z kulturą, rozrywką i rekreacją',
  S: 'S - Pozostała działalność usługowa',
  T: 'T - Gospodarstwa domowe zatrudniające pracowników; gospodarstwa domowe produkujące wyroby i świadczące usługi na własne potrzeby',
  U: 'U - Organizacje i zespoły eksterytorialne',
} as const;

export type PkdSection = keyof typeof PKD_SECTIONS;

// Full PKD codes list with section and division info
export const PKD_CODES = [
  { code: '01.11.Z', label: '01.11.Z - Uprawa zbóż, roślin strączkowych i roślin oleistych na nasiona, z wyłączeniem ryżu', section: 'A', division: '01' },
  { code: '01.12.Z', label: '01.12.Z - Uprawa ryżu', section: 'A', division: '01' },
  { code: '01.13.Z', label: '01.13.Z - Uprawa warzyw, włączając melony oraz uprawa roślin korzeniowych i roślin bulwiastych', section: 'A', division: '01' },
  { code: '01.14.Z', label: '01.14.Z - Uprawa trzciny cukrowej', section: 'A', division: '01' },
  { code: '01.15.Z', label: '01.15.Z - Uprawa tytoniu', section: 'A', division: '01' },
  { code: '01.16.Z', label: '01.16.Z - Uprawa roślin włóknistych', section: 'A', division: '01' },
  { code: '01.19.Z', label: '01.19.Z - Pozostałe uprawy rolne inne niż wieloletnie', section: 'A', division: '01' },
  { code: '01.21.Z', label: '01.21.Z - Uprawa winogron', section: 'A', division: '01' },
  { code: '01.22.Z', label: '01.22.Z - Uprawa drzew i krzewów owocowych tropikalnych i podzwrotnikowych', section: 'A', division: '01' },
  { code: '01.23.Z', label: '01.23.Z - Uprawa drzew i krzewów owocowych cytrusowych', section: 'A', division: '01' },
  { code: '01.24.Z', label: '01.24.Z - Uprawa drzew i krzewów owocowych ziarnkowych i pestkowych', section: 'A', division: '01' },
  { code: '01.25.Z', label: '01.25.Z - Uprawa pozostałych drzew i krzewów owocowych oraz orzechów', section: 'A', division: '01' },
  { code: '01.26.Z', label: '01.26.Z - Uprawa drzew oleistych', section: 'A', division: '01' },
  { code: '01.27.Z', label: '01.27.Z - Uprawa roślin wykorzystywanych do produkcji napojów', section: 'A', division: '01' },
  { code: '01.28.Z', label: '01.28.Z - Uprawa roślin przyprawowych i aromatycznych oraz roślin wykorzystywanych do produkcji leków i wyrobów farmaceutycznych', section: 'A', division: '01' },
  { code: '01.29.Z', label: '01.29.Z - Uprawa pozostałych roślin wieloletnich', section: 'A', division: '01' },
  { code: '01.30.Z', label: '01.30.Z - Rozmnażanie roślin', section: 'A', division: '01' },
  { code: '01.41.Z', label: '01.41.Z - Chów i hodowla bydła mlecznego', section: 'A', division: '01' },
  { code: '01.42.Z', label: '01.42.Z - Chów i hodowla pozostałego bydła i bawołów', section: 'A', division: '01' },
  { code: '01.43.Z', label: '01.43.Z - Chów i hodowla koni i pozostałych zwierząt koniowatych', section: 'A', division: '01' },
  { code: '01.44.Z', label: '01.44.Z - Chów i hodowla wielbłądów i zwierząt wielbłądowatych', section: 'A', division: '01' },
  { code: '01.45.Z', label: '01.45.Z - Chów i hodowla owiec i kóz', section: 'A', division: '01' },
  { code: '01.46.Z', label: '01.46.Z - Chów i hodowla świń', section: 'A', division: '01' },
  { code: '01.47.Z', label: '01.47.Z - Chów i hodowla drobiu', section: 'A', division: '01' },
  { code: '01.49.Z', label: '01.49.Z - Chów i hodowla pozostałych zwierząt', section: 'A', division: '01' },
  { code: '01.50.Z', label: '01.50.Z - Uprawy rolne połączone z chowem i hodowlą zwierząt (działalność mieszana)', section: 'A', division: '01' },
  { code: '01.61.Z', label: '01.61.Z - Działalność usługowa wspomagająca produkcję roślinną', section: 'A', division: '01' },
  { code: '01.62.Z', label: '01.62.Z - Działalność usługowa wspomagająca chów i hodowlę zwierząt gospodarskich', section: 'A', division: '01' },
  { code: '01.63.Z', label: '01.63.Z - Działalność usługowa następująca po zbiorach', section: 'A', division: '01' },
  { code: '01.64.Z', label: '01.64.Z - Obróbka nasion dla celów rozmnażania roślin', section: 'A', division: '01' },
  { code: '01.70.Z', label: '01.70.Z - Łowiectwo i pozyskiwanie zwierząt łownych, włączając działalność usługową', section: 'A', division: '01' },
  { code: '02.10.Z', label: '02.10.Z - Gospodarka leśna i pozostała działalność leśna, z wyłączeniem pozyskiwania produktów leśnych', section: 'A', division: '02' },
  { code: '02.20.Z', label: '02.20.Z - Pozyskiwanie drewna', section: 'A', division: '02' },
  { code: '02.30.Z', label: '02.30.Z - Pozyskiwanie dziko rosnących produktów leśnych, z wyłączeniem drewna', section: 'A', division: '02' },
  { code: '02.40.Z', label: '02.40.Z - Działalność usługowa związana z leśnictwem', section: 'A', division: '02' },
  { code: '03.11.Z', label: '03.11.Z - Rybołówstwo w wodach morskich', section: 'A', division: '03' },
  { code: '03.12.Z', label: '03.12.Z - Rybołówstwo w wodach śródlądowych', section: 'A', division: '03' },
  { code: '03.21.Z', label: '03.21.Z - Chów i hodowla ryb oraz pozostałych organizmów wodnych w wodach morskich', section: 'A', division: '03' },
  { code: '03.22.Z', label: '03.22.Z - Chów i hodowla ryb oraz pozostałych organizmów wodnych w wodach śródlądowych', section: 'A', division: '03' },
  { code: '05.10.Z', label: '05.10.Z - Wydobywanie węgla kamiennego', section: 'B', division: '05' },
  { code: '05.20.Z', label: '05.20.Z - Wydobywanie węgla brunatnego (lignitu)', section: 'B', division: '05' },
  { code: '06.10.Z', label: '06.10.Z - Górnictwo ropy naftowej', section: 'B', division: '06' },
  { code: '06.20.Z', label: '06.20.Z - Górnictwo gazu ziemnego', section: 'B', division: '06' },
  { code: '07.10.Z', label: '07.10.Z - Górnictwo rud żelaza', section: 'B', division: '07' },
  { code: '07.21.Z', label: '07.21.Z - Górnictwo rud uranu i toru', section: 'B', division: '07' },
  { code: '07.29.Z', label: '07.29.Z - Górnictwo pozostałych rud metali nieżelaznych', section: 'B', division: '07' },
  { code: '08.11.Z', label: '08.11.Z - Wydobywanie kamieni ozdobnych oraz kamienia dla potrzeb budownictwa, skał wapiennych, gipsu, kredy i łupków', section: 'B', division: '08' },
  { code: '08.12.Z', label: '08.12.Z - Wydobywanie żwiru i piasku; wydobywanie gliny i kaolinu', section: 'B', division: '08' },
  { code: '08.91.Z', label: '08.91.Z - Wydobywanie minerałów dla przemysłu chemicznego oraz do produkcji nawozów', section: 'B', division: '08' },
  { code: '08.92.Z', label: '08.92.Z - Wydobywanie torfu', section: 'B', division: '08' },
  { code: '08.93.Z', label: '08.93.Z - Wydobywanie soli', section: 'B', division: '08' },
  { code: '08.99.Z', label: '08.99.Z - Pozostałe górnictwo i wydobywanie, gdzie indziej niesklasyfikowane', section: 'B', division: '08' },
  { code: '09.10.Z', label: '09.10.Z - Działalność usługowa wspomagająca eksploatację złóż ropy naftowej i gazu ziemnego', section: 'B', division: '09' },
  { code: '09.90.Z', label: '09.90.Z - Działalność usługowa wspomagająca pozostałe górnictwo i wydobywanie', section: 'B', division: '09' },
  { code: '10.11.Z', label: '10.11.Z - Przetwarzanie i konserwowanie mięsa, z wyłączeniem mięsa z drobiu', section: 'C', division: '10' },
  { code: '10.12.Z', label: '10.12.Z - Przetwarzanie i konserwowanie mięsa z drobiu', section: 'C', division: '10' },
  { code: '10.13.Z', label: '10.13.Z - Produkcja wyrobów z mięsa, włączając wyroby z mięsa drobiowego', section: 'C', division: '10' },
  { code: '10.20.Z', label: '10.20.Z - Przetwarzanie i konserwowanie ryb, skorupiaków i mięczaków', section: 'C', division: '10' },
  { code: '10.31.Z', label: '10.31.Z - Przetwarzanie i konserwowanie ziemniaków', section: 'C', division: '10' },
  { code: '10.32.Z', label: '10.32.Z - Produkcja soków z owoców i warzyw', section: 'C', division: '10' },
  { code: '10.39.Z', label: '10.39.Z - Pozostałe przetwarzanie i konserwowanie owoców i warzyw', section: 'C', division: '10' },
  { code: '10.41.Z', label: '10.41.Z - Produkcja olejów i pozostałych tłuszczów płynnych', section: 'C', division: '10' },
  { code: '10.42.Z', label: '10.42.Z - Produkcja margaryny i podobnych tłuszczów jadalnych', section: 'C', division: '10' },
  { code: '10.51.Z', label: '10.51.Z - Przetwórstwo mleka i wyrób serów', section: 'C', division: '10' },
  { code: '10.52.Z', label: '10.52.Z - Produkcja lodów', section: 'C', division: '10' },
  { code: '10.61.Z', label: '10.61.Z - Wytwarzanie produktów przemiału zbóż', section: 'C', division: '10' },
  { code: '10.62.Z', label: '10.62.Z - Wytwarzanie skrobi i wyrobów skrobiowych', section: 'C', division: '10' },
  { code: '10.71.Z', label: '10.71.Z - Produkcja pieczywa; produkcja świeżych wyrobów ciastkarskich i ciastek', section: 'C', division: '10' },
  { code: '10.72.Z', label: '10.72.Z - Produkcja sucharów i herbatników; produkcja konserwowanych wyrobów ciastkarskich i ciastek', section: 'C', division: '10' },
  { code: '10.73.Z', label: '10.73.Z - Produkcja makaronów, klusek, kuskusu i podobnych wyrobów mącznych', section: 'C', division: '10' },
  { code: '10.81.Z', label: '10.81.Z - Produkcja cukru', section: 'C', division: '10' },
  { code: '10.82.Z', label: '10.82.Z - Produkcja kakao, czekolady i wyrobów cukierniczych', section: 'C', division: '10' },
  { code: '10.83.Z', label: '10.83.Z - Przetwórstwo herbaty i kawy', section: 'C', division: '10' },
  { code: '10.84.Z', label: '10.84.Z - Produkcja przypraw', section: 'C', division: '10' },
  { code: '10.85.Z', label: '10.85.Z - Wytwarzanie gotowych posiłków i dań', section: 'C', division: '10' },
  { code: '10.86.Z', label: '10.86.Z - Produkcja artykułów spożywczych homogenizowanych i żywności dietetycznej', section: 'C', division: '10' },
  { code: '10.89.Z', label: '10.89.Z - Produkcja pozostałych artykułów spożywczych, gdzie indziej niesklasyfikowana', section: 'C', division: '10' },
  { code: '10.91.Z', label: '10.91.Z - Produkcja gotowej paszy dla zwierząt gospodarskich', section: 'C', division: '10' },
  { code: '10.92.Z', label: '10.92.Z - Produkcja gotowej karmy dla zwierząt domowych', section: 'C', division: '10' },
  { code: '11.01.Z', label: '11.01.Z - Destylowanie, rektyfikowanie i mieszanie alkoholi', section: 'C', division: '11' },
  { code: '11.02.Z', label: '11.02.Z - Produkcja win gronowych', section: 'C', division: '11' },
  { code: '11.03.Z', label: '11.03.Z - Produkcja cydru i pozostałych win owocowych', section: 'C', division: '11' },
  { code: '11.04.Z', label: '11.04.Z - Produkcja pozostałych niedestylowanych napojów fermentowanych', section: 'C', division: '11' },
  { code: '11.05.Z', label: '11.05.Z - Produkcja piwa', section: 'C', division: '11' },
  { code: '11.06.Z', label: '11.06.Z - Produkcja słodu', section: 'C', division: '11' },
  { code: '11.07.Z', label: '11.07.Z - Produkcja napojów bezalkoholowych; produkcja wód mineralnych i pozostałych wód butelkowanych', section: 'C', division: '11' },
  { code: '12.00.Z', label: '12.00.Z - PRODUKCJA WYROBÓW TYTONIOWYCH', section: 'C', division: '12' },
  { code: '13.10.A', label: '13.10.A - Produkcja przędzy bawełnianej', section: 'C', division: '13' },
  { code: '13.10.B', label: '13.10.B - Produkcja przędzy wełnianej', section: 'C', division: '13' },
  { code: '13.10.C', label: '13.10.C - Produkcja przędzy z włókien chemicznych', section: 'C', division: '13' },
  { code: '13.10.D', label: '13.10.D - Produkcja przędzy z pozostałych włókien tekstylnych, włączając produkcję nici', section: 'C', division: '13' },
  { code: '13.20.A', label: '13.20.A - Produkcja tkanin bawełnianych', section: 'C', division: '13' },
  { code: '13.20.B', label: '13.20.B - Produkcja tkanin wełnianych', section: 'C', division: '13' },
  { code: '13.20.C', label: '13.20.C - Produkcja tkanin z włókien chemicznych', section: 'C', division: '13' },
  { code: '13.20.D', label: '13.20.D - Produkcja pozostałych tkanin', section: 'C', division: '13' },
  { code: '13.30.Z', label: '13.30.Z - Wykończanie wyrobów włókienniczych', section: 'C', division: '13' },
  { code: '13.91.Z', label: '13.91.Z - Produkcja dzianin metrażowych', section: 'C', division: '13' },
  { code: '13.92.Z', label: '13.92.Z - Produkcja gotowych wyrobów tekstylnych', section: 'C', division: '13' },
  { code: '13.93.Z', label: '13.93.Z - Produkcja dywanów i chodników', section: 'C', division: '13' },
  { code: '13.94.Z', label: '13.94.Z - Produkcja wyrobów powroźniczych, lin, szpagatów i wyrobów sieciowych', section: 'C', division: '13' },
  { code: '13.95.Z', label: '13.95.Z - Produkcja włóknin i wyrobów wykonanych z włóknin, z wyłączeniem odzieży', section: 'C', division: '13' },
  { code: '13.96.Z', label: '13.96.Z - Produkcja pozostałych technicznych i przemysłowych wyrobów tekstylnych', section: 'C', division: '13' },
  { code: '13.99.Z', label: '13.99.Z - Produkcja pozostałych wyrobów tekstylnych, gdzie indziej niesklasyfikowana', section: 'C', division: '13' },
  { code: '14.11.Z', label: '14.11.Z - Produkcja odzieży skórzanej', section: 'C', division: '14' },
  { code: '14.12.Z', label: '14.12.Z - Produkcja odzieży roboczej', section: 'C', division: '14' },
  { code: '14.13.Z', label: '14.13.Z - Produkcja pozostałej odzieży wierzchniej', section: 'C', division: '14' },
  { code: '14.14.Z', label: '14.14.Z - Produkcja bielizny', section: 'C', division: '14' },
  { code: '14.19.Z', label: '14.19.Z - Produkcja pozostałej odzieży i dodatków do odzieży', section: 'C', division: '14' },
  { code: '14.20.Z', label: '14.20.Z - Produkcja wyrobów futrzarskich', section: 'C', division: '14' },
  { code: '14.31.Z', label: '14.31.Z - Produkcja wyrobów pończoszniczych', section: 'C', division: '14' },
  { code: '14.39.Z', label: '14.39.Z - Produkcja pozostałej odzieży dzianej', section: 'C', division: '14' },
  { code: '15.11.Z', label: '15.11.Z - Wyprawa skór, garbowanie; wyprawa i barwienie skór futerkowych', section: 'C', division: '15' },
  { code: '15.12.Z', label: '15.12.Z - Produkcja toreb bagażowych, toreb ręcznych i podobnych wyrobów kaletniczych; produkcja wyrobów rymarskich', section: 'C', division: '15' },
  { code: '15.20.Z', label: '15.20.Z - Produkcja obuwia', section: 'C', division: '15' },
  { code: '16.10.Z', label: '16.10.Z - Produkcja wyrobów tartacznych', section: 'C', division: '16' },
  { code: '16.21.Z', label: '16.21.Z - Produkcja arkuszy fornirowych i płyt wykonanych na bazie drewna', section: 'C', division: '16' },
  { code: '16.22.Z', label: '16.22.Z - Produkcja gotowych parkietów podłogowych', section: 'C', division: '16' },
  { code: '16.23.Z', label: '16.23.Z - Produkcja pozostałych wyrobów stolarskich i ciesielskich dla budownictwa', section: 'C', division: '16' },
  { code: '16.24.Z', label: '16.24.Z - Produkcja opakowań drewnianych', section: 'C', division: '16' },
  { code: '16.29.Z', label: '16.29.Z - Produkcja pozostałych wyrobów z drewna; produkcja wyrobów z korka, słomy i materiałów używanych do wyplatania', section: 'C', division: '16' },
  { code: '17.11.Z', label: '17.11.Z - Produkcja masy włóknistej', section: 'C', division: '17' },
  { code: '17.12.Z', label: '17.12.Z - Produkcja papieru i tektury', section: 'C', division: '17' },
  { code: '17.21.Z', label: '17.21.Z - Produkcja papieru falistego i tektury falistej oraz opakowań z papieru i tektury', section: 'C', division: '17' },
  { code: '17.22.Z', label: '17.22.Z - Produkcja artykułów gospodarstwa domowego, toaletowych i sanitarnych', section: 'C', division: '17' },
  { code: '17.23.Z', label: '17.23.Z - Produkcja artykułów piśmiennych', section: 'C', division: '17' },
  { code: '17.24.Z', label: '17.24.Z - Produkcja tapet', section: 'C', division: '17' },
  { code: '17.29.Z', label: '17.29.Z - Produkcja pozostałych wyrobów z papieru i tektury', section: 'C', division: '17' },
  { code: '18.11.Z', label: '18.11.Z - Drukowanie gazet', section: 'C', division: '18' },
  { code: '18.12.Z', label: '18.12.Z - Pozostałe drukowanie', section: 'C', division: '18' },
  { code: '18.13.Z', label: '18.13.Z - Działalność usługowa związana z przygotowywaniem do druku', section: 'C', division: '18' },
  { code: '18.14.Z', label: '18.14.Z - Introligatorstwo i podobne usługi', section: 'C', division: '18' },
  { code: '18.20.Z', label: '18.20.Z - Reprodukcja zapisanych nośników informacji', section: 'C', division: '18' },
  { code: '19.10.Z', label: '19.10.Z - Wytwarzanie i przetwarzanie koksu', section: 'C', division: '19' },
  { code: '19.20.Z', label: '19.20.Z - Wytwarzanie i przetwarzanie produktów rafinacji ropy naftowej', section: 'C', division: '19' },
  { code: '20.11.Z', label: '20.11.Z - Produkcja gazów technicznych', section: 'C', division: '20' },
  { code: '20.12.Z', label: '20.12.Z - Produkcja barwników i pigmentów', section: 'C', division: '20' },
  { code: '20.13.Z', label: '20.13.Z - Produkcja pozostałych podstawowych chemikaliów nieorganicznych', section: 'C', division: '20' },
  { code: '20.14.Z', label: '20.14.Z - Produkcja pozostałych podstawowych chemikaliów organicznych', section: 'C', division: '20' },
  { code: '20.15.Z', label: '20.15.Z - Produkcja nawozów i związków azotowych', section: 'C', division: '20' },
  { code: '20.16.Z', label: '20.16.Z - Produkcja tworzyw sztucznych w formach podstawowych', section: 'C', division: '20' },
  { code: '20.17.Z', label: '20.17.Z - Produkcja kauczuku syntetycznego w formach podstawowych', section: 'C', division: '20' },
  { code: '20.20.Z', label: '20.20.Z - Produkcja pestycydów i pozostałych środków agrochemicznych', section: 'C', division: '20' },
  { code: '20.30.Z', label: '20.30.Z - Produkcja farb, lakierów i podobnych powłok, farb drukarskich i mas uszczelniających', section: 'C', division: '20' },
  { code: '20.41.Z', label: '20.41.Z - Produkcja mydła i detergentów, środków myjących i czyszczących', section: 'C', division: '20' },
  { code: '20.42.Z', label: '20.42.Z - Produkcja wyrobów kosmetycznych i toaletowych', section: 'C', division: '20' },
  { code: '20.51.Z', label: '20.51.Z - Produkcja materiałów wybuchowych', section: 'C', division: '20' },
  { code: '20.52.Z', label: '20.52.Z - Produkcja klejów', section: 'C', division: '20' },
  { code: '20.53.Z', label: '20.53.Z - Produkcja olejków eterycznych', section: 'C', division: '20' },
  { code: '20.59.Z', label: '20.59.Z - Produkcja pozostałych wyrobów chemicznych, gdzie indziej niesklasyfikowana', section: 'C', division: '20' },
  { code: '20.60.Z', label: '20.60.Z - Produkcja włókien chemicznych', section: 'C', division: '20' },
  { code: '21.10.Z', label: '21.10.Z - Produkcja podstawowych substancji farmaceutycznych', section: 'C', division: '21' },
  { code: '21.20.Z', label: '21.20.Z - Produkcja leków i pozostałych wyrobów farmaceutycznych', section: 'C', division: '21' },
  { code: '22.11.Z', label: '22.11.Z - Produkcja opon i dętek z gumy; bieżnikowanie i regenerowanie opon z gumy', section: 'C', division: '22' },
  { code: '22.19.Z', label: '22.19.Z - Produkcja pozostałych wyrobów z gumy', section: 'C', division: '22' },
  { code: '22.21.Z', label: '22.21.Z - Produkcja płyt, arkuszy, rur i kształtowników z tworzyw sztucznych', section: 'C', division: '22' },
  { code: '22.22.Z', label: '22.22.Z - Produkcja opakowań z tworzyw sztucznych', section: 'C', division: '22' },
  { code: '22.23.Z', label: '22.23.Z - Produkcja wyrobów dla budownictwa z tworzyw sztucznych', section: 'C', division: '22' },
  { code: '22.29.Z', label: '22.29.Z - Produkcja pozostałych wyrobów z tworzyw sztucznych', section: 'C', division: '22' },
  { code: '23.11.Z', label: '23.11.Z - Produkcja szkła płaskiego', section: 'C', division: '23' },
  { code: '23.12.Z', label: '23.12.Z - Kształtowanie i obróbka szkła płaskiego', section: 'C', division: '23' },
  { code: '23.13.Z', label: '23.13.Z - Produkcja szkła gospodarczego', section: 'C', division: '23' },
  { code: '23.14.Z', label: '23.14.Z - Produkcja włókien szklanych', section: 'C', division: '23' },
  { code: '23.19.Z', label: '23.19.Z - Produkcja i obróbka pozostałego szkła, włączając szkło techniczne', section: 'C', division: '23' },
  { code: '23.20.Z', label: '23.20.Z - Produkcja wyrobów ogniotrwałych', section: 'C', division: '23' },
  { code: '23.31.Z', label: '23.31.Z - Produkcja ceramicznych kafli i płytek', section: 'C', division: '23' },
  { code: '23.32.Z', label: '23.32.Z - Produkcja cegieł, dachówek i materiałów budowlanych, z wypalanej gliny', section: 'C', division: '23' },
  { code: '23.41.Z', label: '23.41.Z - Produkcja ceramicznych wyrobów stołowych i ozdobnych', section: 'C', division: '23' },
  { code: '23.42.Z', label: '23.42.Z - Produkcja ceramicznych wyrobów sanitarnych', section: 'C', division: '23' },
  { code: '23.43.Z', label: '23.43.Z - Produkcja ceramicznych izolatorów i osłon izolacyjnych', section: 'C', division: '23' },
  { code: '23.44.Z', label: '23.44.Z - Produkcja pozostałych technicznych wyrobów ceramicznych', section: 'C', division: '23' },
  { code: '23.49.Z', label: '23.49.Z - Produkcja pozostałych wyrobów ceramicznych', section: 'C', division: '23' },
  { code: '23.51.Z', label: '23.51.Z - Produkcja cementu', section: 'C', division: '23' },
  { code: '23.52.Z', label: '23.52.Z - Produkcja wapna i gipsu', section: 'C', division: '23' },
  { code: '23.61.Z', label: '23.61.Z - Produkcja wyrobów budowlanych z betonu', section: 'C', division: '23' },
  { code: '23.62.Z', label: '23.62.Z - Produkcja wyrobów budowlanych z gipsu', section: 'C', division: '23' },
  { code: '23.63.Z', label: '23.63.Z - Produkcja masy betonowej prefabrykowanej', section: 'C', division: '23' },
  { code: '23.64.Z', label: '23.64.Z - Produkcja zaprawy murarskiej', section: 'C', division: '23' },
  { code: '23.65.Z', label: '23.65.Z - Produkcja cementu wzmocnionego włóknem', section: 'C', division: '23' },
  { code: '23.69.Z', label: '23.69.Z - Produkcja pozostałych wyrobów z betonu, gipsu i cementu', section: 'C', division: '23' },
  { code: '23.70.Z', label: '23.70.Z - Cięcie, formowanie i wykańczanie kamienia', section: 'C', division: '23' },
  { code: '23.91.Z', label: '23.91.Z - Produkcja wyrobów ściernych', section: 'C', division: '23' },
  { code: '23.99.Z', label: '23.99.Z - Produkcja pozostałych wyrobów z mineralnych surowców niemetalicznych, gdzie indziej niesklasyfikowana', section: 'C', division: '23' },
  { code: '24.10.Z', label: '24.10.Z - Produkcja surówki, żelazostopów, żeliwa i stali oraz wyrobów hutniczych', section: 'C', division: '24' },
  { code: '24.20.Z', label: '24.20.Z - Produkcja rur, przewodów, kształtowników zamkniętych i łączników, ze stali', section: 'C', division: '24' },
  { code: '24.31.Z', label: '24.31.Z - Produkcja prętów ciągnionych na zimno', section: 'C', division: '24' },
  { code: '24.32.Z', label: '24.32.Z - Produkcja wyrobów płaskich walcowanych na zimno', section: 'C', division: '24' },
  { code: '24.33.Z', label: '24.33.Z - Produkcja wyrobów formowanych na zimno', section: 'C', division: '24' },
  { code: '24.34.Z', label: '24.34.Z - Produkcja drutu', section: 'C', division: '24' },
  { code: '24.41.Z', label: '24.41.Z - Produkcja metali szlachetnych', section: 'C', division: '24' },
  { code: '24.42.A', label: '24.42.A - Produkcja aluminium hutniczego', section: 'C', division: '24' },
  { code: '24.42.B', label: '24.42.B - Produkcja wyrobów z aluminium i stopów aluminium', section: 'C', division: '24' },
  { code: '24.43.Z', label: '24.43.Z - Produkcja ołowiu, cynku i cyny', section: 'C', division: '24' },
  { code: '24.44.Z', label: '24.44.Z - Produkcja miedzi', section: 'C', division: '24' },
  { code: '24.45.Z', label: '24.45.Z - Produkcja pozostałych metali nieżelaznych', section: 'C', division: '24' },
  { code: '24.46.Z', label: '24.46.Z - Wytwarzanie paliw jądrowych', section: 'C', division: '24' },
  { code: '24.51.Z', label: '24.51.Z - Odlewnictwo żeliwa', section: 'C', division: '24' },
  { code: '24.52.Z', label: '24.52.Z - Odlewnictwo staliwa', section: 'C', division: '24' },
  { code: '24.53.Z', label: '24.53.Z - Odlewnictwo metali lekkich', section: 'C', division: '24' },
  { code: '24.54.A', label: '24.54.A - Odlewnictwo miedzi i stopów miedzi', section: 'C', division: '24' },
  { code: '24.54.B', label: '24.54.B - Odlewnictwo pozostałych metali nieżelaznych, gdzie indziej niesklasyfikowane', section: 'C', division: '24' },
  { code: '25.11.Z', label: '25.11.Z - Produkcja konstrukcji metalowych i ich części', section: 'C', division: '25' },
  { code: '25.12.Z', label: '25.12.Z - Produkcja metalowych elementów stolarki budowlanej', section: 'C', division: '25' },
  { code: '25.21.Z', label: '25.21.Z - Produkcja grzejników i kotłów centralnego ogrzewania', section: 'C', division: '25' },
  { code: '25.29.Z', label: '25.29.Z - Produkcja pozostałych zbiorników, cystern i pojemników metalowych', section: 'C', division: '25' },
  { code: '25.30.Z', label: '25.30.Z - Produkcja wytwornic pary, z wyłączeniem kotłów do centralnego ogrzewania gorącą wodą', section: 'C', division: '25' },
  { code: '25.40.Z', label: '25.40.Z - Produkcja broni i amunicji', section: 'C', division: '25' },
  { code: '25.50.Z', label: '25.50.Z - Kucie, prasowanie, wytłaczanie i walcowanie metali; metalurgia proszków', section: 'C', division: '25' },
  { code: '25.61.Z', label: '25.61.Z - Obróbka metali i nakładanie powłok na metale', section: 'C', division: '25' },
  { code: '25.62.Z', label: '25.62.Z - Obróbka mechaniczna elementów metalowych', section: 'C', division: '25' },
  { code: '25.71.Z', label: '25.71.Z - Produkcja wyrobów nożowniczych i sztućców', section: 'C', division: '25' },
  { code: '25.72.Z', label: '25.72.Z - Produkcja zamków i zawiasów', section: 'C', division: '25' },
  { code: '25.73.Z', label: '25.73.Z - Produkcja narzędzi', section: 'C', division: '25' },
  { code: '25.91.Z', label: '25.91.Z - Produkcja pojemników metalowych', section: 'C', division: '25' },
  { code: '25.92.Z', label: '25.92.Z - Produkcja opakowań z metali', section: 'C', division: '25' },
  { code: '25.93.Z', label: '25.93.Z - Produkcja wyrobów z drutu, łańcuchów i sprężyn', section: 'C', division: '25' },
  { code: '25.94.Z', label: '25.94.Z - Produkcja złączy i śrub', section: 'C', division: '25' },
  { code: '25.99.Z', label: '25.99.Z - Produkcja pozostałych gotowych wyrobów metalowych, gdzie indziej niesklasyfikowana', section: 'C', division: '25' },
  { code: '26.11.Z', label: '26.11.Z - Produkcja elementów elektronicznych', section: 'C', division: '26' },
  { code: '26.12.Z', label: '26.12.Z - Produkcja elektronicznych obwodów drukowanych', section: 'C', division: '26' },
  { code: '26.20.Z', label: '26.20.Z - Produkcja komputerów i urządzeń peryferyjnych', section: 'C', division: '26' },
  { code: '26.30.Z', label: '26.30.Z - Produkcja sprzętu (tele)komunikacyjnego', section: 'C', division: '26' },
  { code: '26.40.Z', label: '26.40.Z - Produkcja elektronicznego sprzętu powszechnego użytku', section: 'C', division: '26' },
  { code: '26.51.Z', label: '26.51.Z - Produkcja instrumentów i przyrządów pomiarowych, kontrolnych i nawigacyjnych', section: 'C', division: '26' },
  { code: '26.52.Z', label: '26.52.Z - Produkcja zegarków i zegarów', section: 'C', division: '26' },
  { code: '26.60.Z', label: '26.60.Z - Produkcja urządzeń napromieniowujących, sprzętu elektromedycznego i elektroterapeutycznego', section: 'C', division: '26' },
  { code: '26.70.Z', label: '26.70.Z - Produkcja instrumentów optycznych i sprzętu fotograficznego', section: 'C', division: '26' },
  { code: '26.80.Z', label: '26.80.Z - Produkcja magnetycznych i optycznych niezapisanych nośników informacji', section: 'C', division: '26' },
  { code: '27.11.Z', label: '27.11.Z - Produkcja elektrycznych silników, prądnic i transformatorów', section: 'C', division: '27' },
  { code: '27.12.Z', label: '27.12.Z - Produkcja aparatury rozdzielczej i sterowniczej energii elektrycznej', section: 'C', division: '27' },
  { code: '27.20.Z', label: '27.20.Z - Produkcja baterii i akumulatorów', section: 'C', division: '27' },
  { code: '27.31.Z', label: '27.31.Z - Produkcja kabli światłowodowych', section: 'C', division: '27' },
  { code: '27.32.Z', label: '27.32.Z - Produkcja pozostałych elektronicznych i elektrycznych przewodów i kabli', section: 'C', division: '27' },
  { code: '27.33.Z', label: '27.33.Z - Produkcja sprzętu instalacyjnego', section: 'C', division: '27' },
  { code: '27.40.Z', label: '27.40.Z - Produkcja elektrycznego sprzętu oświetleniowego', section: 'C', division: '27' },
  { code: '27.51.Z', label: '27.51.Z - Produkcja elektrycznego sprzętu gospodarstwa domowego', section: 'C', division: '27' },
  { code: '27.52.Z', label: '27.52.Z - Produkcja nieelektrycznego sprzętu gospodarstwa domowego', section: 'C', division: '27' },
  { code: '27.90.Z', label: '27.90.Z - Produkcja pozostałego sprzętu elektrycznego', section: 'C', division: '27' },
  { code: '28.11.Z', label: '28.11.Z - Produkcja silników i turbin, z wyłączeniem silników lotniczych, samochodowych i motocyklowych', section: 'C', division: '28' },
  { code: '28.12.Z', label: '28.12.Z - Produkcja sprzętu i wyposażenia do napędu hydraulicznego i pneumatycznego', section: 'C', division: '28' },
  { code: '28.13.Z', label: '28.13.Z - Produkcja pozostałych pomp i sprężarek', section: 'C', division: '28' },
  { code: '28.14.Z', label: '28.14.Z - Produkcja pozostałych kurków i zaworów', section: 'C', division: '28' },
  { code: '28.15.Z', label: '28.15.Z - Produkcja łożysk, kół zębatych, przekładni zębatych i elementów napędowych', section: 'C', division: '28' },
  { code: '28.21.Z', label: '28.21.Z - Produkcja pieców, palenisk i palników piecowych', section: 'C', division: '28' },
  { code: '28.22.Z', label: '28.22.Z - Produkcja urządzeń dźwigowych i chwytaków', section: 'C', division: '28' },
  { code: '28.23.Z', label: '28.23.Z - Produkcja maszyn i sprzętu biurowego, z wyłączeniem komputerów i urządzeń peryferyjnych', section: 'C', division: '28' },
  { code: '28.24.Z', label: '28.24.Z - Produkcja narzędzi ręcznych mechanicznych', section: 'C', division: '28' },
  { code: '28.25.Z', label: '28.25.Z - Produkcja przemysłowych urządzeń chłodniczych i wentylacyjnych', section: 'C', division: '28' },
  { code: '28.29.Z', label: '28.29.Z - Produkcja pozostałych maszyn ogólnego przeznaczenia, gdzie indziej niesklasyfikowana', section: 'C', division: '28' },
  { code: '28.30.Z', label: '28.30.Z - Produkcja maszyn dla rolnictwa i leśnictwa', section: 'C', division: '28' },
  { code: '28.41.Z', label: '28.41.Z - Produkcja maszyn do obróbki metalu', section: 'C', division: '28' },
  { code: '28.49.Z', label: '28.49.Z - Produkcja pozostałych narzędzi mechanicznych', section: 'C', division: '28' },
  { code: '28.91.Z', label: '28.91.Z - Produkcja maszyn dla metalurgii', section: 'C', division: '28' },
  { code: '28.92.Z', label: '28.92.Z - Produkcja maszyn dla górnictwa i do wydobywania oraz budownictwa', section: 'C', division: '28' },
  { code: '28.93.Z', label: '28.93.Z - Produkcja maszyn stosowanych w przetwórstwie żywności, tytoniu i produkcji napojów', section: 'C', division: '28' },
  { code: '28.94.Z', label: '28.94.Z - Produkcja maszyn dla przemysłu tekstylnego, odzieżowego i skórzanego', section: 'C', division: '28' },
  { code: '28.95.Z', label: '28.95.Z - Produkcja maszyn dla przemysłu papierniczego', section: 'C', division: '28' },
  { code: '28.96.Z', label: '28.96.Z - Produkcja maszyn do obróbki gumy lub tworzyw sztucznych oraz wytwarzania wyrobów z tych materiałów', section: 'C', division: '28' },
  { code: '28.99.Z', label: '28.99.Z - Produkcja pozostałych maszyn specjalnego przeznaczenia, gdzie indziej niesklasyfikowana', section: 'C', division: '28' },
  { code: '29.10.A', label: '29.10.A - Produkcja silników do pojazdów samochodowych (z wyłączeniem motocykli) oraz do ciągników rolniczych', section: 'C', division: '29' },
  { code: '29.10.B', label: '29.10.B - Produkcja samochodów osobowych', section: 'C', division: '29' },
  { code: '29.10.C', label: '29.10.C - Produkcja autobusów', section: 'C', division: '29' },
  { code: '29.10.D', label: '29.10.D - Produkcja pojazdów samochodowych przeznaczonych do przewozu towarów', section: 'C', division: '29' },
  { code: '29.10.E', label: '29.10.E - Produkcja pozostałych pojazdów samochodowych, z wyłączeniem motocykli', section: 'C', division: '29' },
  { code: '29.20.Z', label: '29.20.Z - Produkcja nadwozi do pojazdów silnikowych; produkcja przyczep i naczep', section: 'C', division: '29' },
  { code: '29.31.Z', label: '29.31.Z - Produkcja wyposażenia elektrycznego i elektronicznego do pojazdów silnikowych', section: 'C', division: '29' },
  { code: '29.32.Z', label: '29.32.Z - Produkcja pozostałych części i akcesoriów do pojazdów silnikowych, z wyłączeniem motocykli', section: 'C', division: '29' },
  { code: '30.11.Z', label: '30.11.Z - Produkcja statków i konstrukcji pływających', section: 'C', division: '30' },
  { code: '30.12.Z', label: '30.12.Z - Produkcja łodzi wycieczkowych i sportowych', section: 'C', division: '30' },
  { code: '30.20.Z', label: '30.20.Z - Produkcja lokomotyw kolejowych oraz taboru szynowego', section: 'C', division: '30' },
  { code: '30.30.Z', label: '30.30.Z - Produkcja statków powietrznych, statków kosmicznych i podobnych maszyn', section: 'C', division: '30' },
  { code: '30.40.Z', label: '30.40.Z - Produkcja wojskowych pojazdów bojowych', section: 'C', division: '30' },
  { code: '30.91.Z', label: '30.91.Z - Produkcja motocykli', section: 'C', division: '30' },
  { code: '30.92.Z', label: '30.92.Z - Produkcja rowerów i wózków inwalidzkich', section: 'C', division: '30' },
  { code: '30.99.Z', label: '30.99.Z - Produkcja pozostałego sprzętu transportowego, gdzie indziej niesklasyfikowana', section: 'C', division: '30' },
  { code: '31.01.Z', label: '31.01.Z - Produkcja mebli biurowych i sklepowych', section: 'C', division: '31' },
  { code: '31.02.Z', label: '31.02.Z - Produkcja mebli kuchennych', section: 'C', division: '31' },
  { code: '31.03.Z', label: '31.03.Z - Produkcja materaców', section: 'C', division: '31' },
  { code: '31.09.Z', label: '31.09.Z - Produkcja pozostałych mebli', section: 'C', division: '31' },
  { code: '32.11.Z', label: '32.11.Z - Produkcja monet', section: 'C', division: '32' },
  { code: '32.12.Z', label: '32.12.Z - Produkcja wyrobów jubilerskich i podobnych', section: 'C', division: '32' },
  { code: '32.13.Z', label: '32.13.Z - Produkcja sztucznej biżuterii i wyrobów podobnych', section: 'C', division: '32' },
  { code: '32.20.Z', label: '32.20.Z - Produkcja instrumentów muzycznych', section: 'C', division: '32' },
  { code: '32.30.Z', label: '32.30.Z - Produkcja sprzętu sportowego', section: 'C', division: '32' },
  { code: '32.40.Z', label: '32.40.Z - Produkcja gier i zabawek', section: 'C', division: '32' },
  { code: '32.50.Z', label: '32.50.Z - Produkcja urządzeń, instrumentów oraz wyrobów medycznych, włączając dentystyczne', section: 'C', division: '32' },
  { code: '32.91.Z', label: '32.91.Z - Produkcja mioteł, szczotek i pędzli', section: 'C', division: '32' },
  { code: '32.99.Z', label: '32.99.Z - Produkcja pozostałych wyrobów, gdzie indziej niesklasyfikowana', section: 'C', division: '32' },
  { code: '33.11.Z', label: '33.11.Z - Naprawa i konserwacja metalowych wyrobów gotowych', section: 'C', division: '33' },
  { code: '33.12.Z', label: '33.12.Z - Naprawa i konserwacja maszyn', section: 'C', division: '33' },
  { code: '33.13.Z', label: '33.13.Z - Naprawa i konserwacja urządzeń elektronicznych i optycznych', section: 'C', division: '33' },
  { code: '33.14.Z', label: '33.14.Z - Naprawa i konserwacja urządzeń elektrycznych', section: 'C', division: '33' },
  { code: '33.15.Z', label: '33.15.Z - Naprawa i konserwacja statków i łodzi', section: 'C', division: '33' },
  { code: '33.16.Z', label: '33.16.Z - Naprawa i konserwacja statków powietrznych i statków kosmicznych', section: 'C', division: '33' },
  { code: '33.17.Z', label: '33.17.Z - Naprawa i konserwacja pozostałego sprzętu transportowego', section: 'C', division: '33' },
  { code: '33.19.Z', label: '33.19.Z - Naprawa i konserwacja pozostałego sprzętu i wyposażenia', section: 'C', division: '33' },
  { code: '33.20.Z', label: '33.20.Z - Instalowanie maszyn przemysłowych, sprzętu i wyposażenia', section: 'C', division: '33' },
  { code: '35.11.Z', label: '35.11.Z - Wytwarzanie energii elektrycznej', section: 'D', division: '35' },
  { code: '35.12.Z', label: '35.12.Z - Przesyłanie energii elektrycznej', section: 'D', division: '35' },
  { code: '35.13.Z', label: '35.13.Z - Dystrybucja energii elektrycznej', section: 'D', division: '35' },
  { code: '35.14.Z', label: '35.14.Z - Handel energią elektryczną', section: 'D', division: '35' },
  { code: '35.21.Z', label: '35.21.Z - Wytwarzanie paliw gazowych', section: 'D', division: '35' },
  { code: '35.22.Z', label: '35.22.Z - Dystrybucja paliw gazowych w systemie sieciowym', section: 'D', division: '35' },
  { code: '35.23.Z', label: '35.23.Z - Handel paliwami gazowymi w systemie sieciowym', section: 'D', division: '35' },
  { code: '35.30.Z', label: '35.30.Z - Wytwarzanie i zaopatrywanie w parę wodną, gorącą wodę i powietrze do układów klimatyzacyjnych', section: 'D', division: '35' },
  { code: '36.00.Z', label: '36.00.Z - POBÓR, UZDATNIANIE I DOSTARCZANIE WODY', section: 'E', division: '36' },
  { code: '37.00.Z', label: '37.00.Z - ODPROWADZANIE I OCZYSZCZANIE ŚCIEKÓW', section: 'E', division: '37' },
  { code: '38.11.Z', label: '38.11.Z - Zbieranie odpadów innych niż niebezpieczne', section: 'E', division: '38' },
  { code: '38.12.Z', label: '38.12.Z - Zbieranie odpadów niebezpiecznych', section: 'E', division: '38' },
  { code: '38.21.Z', label: '38.21.Z - Obróbka i usuwanie odpadów innych niż niebezpieczne', section: 'E', division: '38' },
  { code: '38.22.Z', label: '38.22.Z - Przetwarzanie i unieszkodliwianie odpadów niebezpiecznych', section: 'E', division: '38' },
  { code: '38.31.Z', label: '38.31.Z - Demontaż wyrobów zużytych', section: 'E', division: '38' },
  { code: '38.32.Z', label: '38.32.Z - Odzysk surowców z materiałów segregowanych', section: 'E', division: '38' },
  { code: '39.00.Z', label: '39.00.Z - DZIAŁALNOŚĆ ZWIĄZANA Z REKULTYWACJĄ I POZOSTAŁA DZIAŁALNOŚĆ USŁUGOWA ZWIĄZANA Z GOSPODARKĄ ODPADAMI', section: 'E', division: '39' },
  { code: '41.10.Z', label: '41.10.Z - Realizacja projektów budowlanych związanych ze wznoszeniem budynków', section: 'F', division: '41' },
  { code: '41.20.Z', label: '41.20.Z - Roboty budowlane związane ze wznoszeniem budynków mieszkalnych i niemieszkalnych', section: 'F', division: '41' },
  { code: '42.11.Z', label: '42.11.Z - Roboty związane z budową dróg i autostrad', section: 'F', division: '42' },
  { code: '42.12.Z', label: '42.12.Z - Roboty związane z budową dróg szynowych i kolei podziemnej', section: 'F', division: '42' },
  { code: '42.13.Z', label: '42.13.Z - Roboty związane z budową mostów i tuneli', section: 'F', division: '42' },
  { code: '42.21.Z', label: '42.21.Z - Roboty związane z budową rurociągów przesyłowych i sieci rozdzielczych', section: 'F', division: '42' },
  { code: '42.22.Z', label: '42.22.Z - Roboty związane z budową linii telekomunikacyjnych i elektroenergetycznych', section: 'F', division: '42' },
  { code: '42.91.Z', label: '42.91.Z - Roboty związane z budową obiektów inżynierii wodnej', section: 'F', division: '42' },
  { code: '42.99.Z', label: '42.99.Z - Roboty związane z budową pozostałych obiektów inżynierii lądowej i wodnej, gdzie indziej niesklasyfikowane', section: 'F', division: '42' },
  { code: '43.11.Z', label: '43.11.Z - Rozbiórka i burzenie obiektów budowlanych', section: 'F', division: '43' },
  { code: '43.12.Z', label: '43.12.Z - Przygotowanie terenu pod budowę', section: 'F', division: '43' },
  { code: '43.13.Z', label: '43.13.Z - Wykonywanie wykopów i wierceń geologiczno-inżynierskich', section: 'F', division: '43' },
  { code: '43.21.Z', label: '43.21.Z - Wykonywanie instalacji elektrycznych', section: 'F', division: '43' },
  { code: '43.22.Z', label: '43.22.Z - Wykonywanie instalacji wodno-kanalizacyjnych, cieplnych, gazowych i klimatyzacyjnych', section: 'F', division: '43' },
  { code: '43.29.Z', label: '43.29.Z - Wykonywanie pozostałych instalacji budowlanych', section: 'F', division: '43' },
  { code: '43.31.Z', label: '43.31.Z - Tynkowanie', section: 'F', division: '43' },
  { code: '43.32.Z', label: '43.32.Z - Zakładanie stolarki budowlanej', section: 'F', division: '43' },
  { code: '43.33.Z', label: '43.33.Z - Posadzkarstwo; tapetowanie i oblicowywanie ścian', section: 'F', division: '43' },
  { code: '43.34.Z', label: '43.34.Z - Malowanie i szklenie', section: 'F', division: '43' },
  { code: '43.39.Z', label: '43.39.Z - Wykonywanie pozostałych robót budowlanych wykończeniowych', section: 'F', division: '43' },
  { code: '43.91.Z', label: '43.91.Z - Wykonywanie konstrukcji i pokryć dachowych', section: 'F', division: '43' },
  { code: '43.99.Z', label: '43.99.Z - Pozostałe specjalistyczne roboty budowlane, gdzie indziej niesklasyfikowane', section: 'F', division: '43' },
  { code: '45.11.Z', label: '45.11.Z - Sprzedaż hurtowa i detaliczna samochodów osobowych i furgonetek', section: 'G', division: '45' },
  { code: '45.19.Z', label: '45.19.Z - Sprzedaż hurtowa i detaliczna pozostałych pojazdów samochodowych, z wyłączeniem motocykli', section: 'G', division: '45' },
  { code: '45.20.Z', label: '45.20.Z - Konserwacja i naprawa pojazdów samochodowych, z wyłączeniem motocykli', section: 'G', division: '45' },
  { code: '45.31.Z', label: '45.31.Z - Sprzedaż hurtowa części i akcesoriów do pojazdów samochodowych, z wyłączeniem motocykli', section: 'G', division: '45' },
  { code: '45.32.Z', label: '45.32.Z - Sprzedaż detaliczna części i akcesoriów do pojazdów samochodowych, z wyłączeniem motocykli', section: 'G', division: '45' },
  { code: '45.40.Z', label: '45.40.Z - Sprzedaż hurtowa i detaliczna motocykli, ich naprawa i konserwacja oraz sprzedaż hurtowa i detaliczna części i akcesoriów do nich', section: 'G', division: '45' },
  { code: '46.11.Z', label: '46.11.Z - Działalność agentów zajmujących się sprzedażą płodów rolnych, żywych zwierząt, surowców dla przemysłu tekstylnego i półproduktów', section: 'G', division: '46' },
  { code: '46.12.Z', label: '46.12.Z - Działalność agentów zajmujących się sprzedażą paliw, rud, metali i chemikaliów przemysłowych', section: 'G', division: '46' },
  { code: '46.13.Z', label: '46.13.Z - Działalność agentów zajmujących się sprzedażą drewna i materiałów budowlanych', section: 'G', division: '46' },
  { code: '46.14.Z', label: '46.14.Z - Działalność agentów zajmujących się sprzedażą maszyn, urządzeń przemysłowych, statków i samolotów', section: 'G', division: '46' },
  { code: '46.15.Z', label: '46.15.Z - Działalność agentów zajmujących się sprzedażą mebli, artykułów gospodarstwa domowego i drobnych wyrobów metalowych', section: 'G', division: '46' },
  { code: '46.16.Z', label: '46.16.Z - Działalność agentów zajmujących się sprzedażą wyrobów tekstylnych, odzieży, wyrobów futrzarskich, obuwia i artykułów skórzanych', section: 'G', division: '46' },
  { code: '46.17.Z', label: '46.17.Z - Działalność agentów zajmujących się sprzedażą żywności, napojów i wyrobów tytoniowych', section: 'G', division: '46' },
  { code: '46.18.Z', label: '46.18.Z - Działalność agentów specjalizujących się w sprzedaży pozostałych określonych towarów', section: 'G', division: '46' },
  { code: '46.19.Z', label: '46.19.Z - Działalność agentów zajmujących się sprzedażą towarów różnego rodzaju', section: 'G', division: '46' },
  { code: '46.21.Z', label: '46.21.Z - Sprzedaż hurtowa zboża, nieprzetworzonego tytoniu, nasion i pasz dla zwierząt', section: 'G', division: '46' },
  { code: '46.22.Z', label: '46.22.Z - Sprzedaż hurtowa kwiatów i roślin', section: 'G', division: '46' },
  { code: '46.23.Z', label: '46.23.Z - Sprzedaż hurtowa żywych zwierząt', section: 'G', division: '46' },
  { code: '46.24.Z', label: '46.24.Z - Sprzedaż hurtowa skór', section: 'G', division: '46' },
  { code: '46.31.Z', label: '46.31.Z - Sprzedaż hurtowa owoców i warzyw', section: 'G', division: '46' },
  { code: '46.32.Z', label: '46.32.Z - Sprzedaż hurtowa mięsa i wyrobów z mięsa', section: 'G', division: '46' },
  { code: '46.33.Z', label: '46.33.Z - Sprzedaż hurtowa mleka, wyrobów mleczarskich, jaj, olejów i tłuszczów jadalnych', section: 'G', division: '46' },
  { code: '46.34.A', label: '46.34.A - Sprzedaż hurtowa napojów alkoholowych', section: 'G', division: '46' },
  { code: '46.34.B', label: '46.34.B - Sprzedaż hurtowa napojów bezalkoholowych', section: 'G', division: '46' },
  { code: '46.35.Z', label: '46.35.Z - Sprzedaż hurtowa wyrobów tytoniowych', section: 'G', division: '46' },
  { code: '46.36.Z', label: '46.36.Z - Sprzedaż hurtowa cukru, czekolady, wyrobów cukierniczych i piekarskich', section: 'G', division: '46' },
  { code: '46.37.Z', label: '46.37.Z - Sprzedaż hurtowa herbaty, kawy, kakao i przypraw', section: 'G', division: '46' },
  { code: '46.38.Z', label: '46.38.Z - Sprzedaż hurtowa pozostałej żywności, włączając ryby, skorupiaki i mięczaki', section: 'G', division: '46' },
  { code: '46.39.Z', label: '46.39.Z - Sprzedaż hurtowa niewyspecjalizowana żywności, napojów i wyrobów tytoniowych', section: 'G', division: '46' },
  { code: '46.41.Z', label: '46.41.Z - Sprzedaż hurtowa wyrobów tekstylnych', section: 'G', division: '46' },
  { code: '46.42.Z', label: '46.42.Z - Sprzedaż hurtowa odzieży i obuwia', section: 'G', division: '46' },
  { code: '46.43.Z', label: '46.43.Z - Sprzedaż hurtowa elektrycznych artykułów użytku domowego', section: 'G', division: '46' },
  { code: '46.44.Z', label: '46.44.Z - Sprzedaż hurtowa wyrobów porcelanowych, ceramicznych i szklanych oraz środków czyszczących', section: 'G', division: '46' },
  { code: '46.45.Z', label: '46.45.Z - Sprzedaż hurtowa perfum i kosmetyków', section: 'G', division: '46' },
  { code: '46.46.Z', label: '46.46.Z - Sprzedaż hurtowa wyrobów farmaceutycznych i medycznych', section: 'G', division: '46' },
  { code: '46.47.Z', label: '46.47.Z - Sprzedaż hurtowa mebli, dywanów i sprzętu oświetleniowego', section: 'G', division: '46' },
  { code: '46.48.Z', label: '46.48.Z - Sprzedaż hurtowa zegarków, zegarów i biżuterii', section: 'G', division: '46' },
  { code: '46.49.Z', label: '46.49.Z - Sprzedaż hurtowa pozostałych artykułów użytku domowego', section: 'G', division: '46' },
  { code: '46.51.Z', label: '46.51.Z - Sprzedaż hurtowa komputerów, urządzeń peryferyjnych i oprogramowania', section: 'G', division: '46' },
  { code: '46.52.Z', label: '46.52.Z - Sprzedaż hurtowa sprzętu elektronicznego i telekomunikacyjnego oraz części do niego', section: 'G', division: '46' },
  { code: '46.61.Z', label: '46.61.Z - Sprzedaż hurtowa maszyn i urządzeń rolniczych oraz dodatkowego wyposażenia', section: 'G', division: '46' },
  { code: '46.62.Z', label: '46.62.Z - Sprzedaż hurtowa obrabiarek', section: 'G', division: '46' },
  { code: '46.63.Z', label: '46.63.Z - Sprzedaż hurtowa maszyn wykorzystywanych w górnictwie, budownictwie oraz inżynierii lądowej i wodnej', section: 'G', division: '46' },
  { code: '46.64.Z', label: '46.64.Z - Sprzedaż hurtowa maszyn dla przemysłu tekstylnego oraz maszyn do szycia i maszyn dziewiarskich', section: 'G', division: '46' },
  { code: '46.65.Z', label: '46.65.Z - Sprzedaż hurtowa mebli biurowych', section: 'G', division: '46' },
  { code: '46.66.Z', label: '46.66.Z - Sprzedaż hurtowa pozostałych maszyn i urządzeń biurowych', section: 'G', division: '46' },
  { code: '46.69.Z', label: '46.69.Z - Sprzedaż hurtowa pozostałych maszyn i urządzeń', section: 'G', division: '46' },
  { code: '46.71.Z', label: '46.71.Z - Sprzedaż hurtowa paliw i produktów pochodnych', section: 'G', division: '46' },
  { code: '46.72.Z', label: '46.72.Z - Sprzedaż hurtowa metali i rud metali', section: 'G', division: '46' },
  { code: '46.73.Z', label: '46.73.Z - Sprzedaż hurtowa drewna, materiałów budowlanych i wyposażenia sanitarnego', section: 'G', division: '46' },
  { code: '46.74.Z', label: '46.74.Z - Sprzedaż hurtowa wyrobów metalowych oraz sprzętu i dodatkowego wyposażenia hydraulicznego i grzejnego', section: 'G', division: '46' },
  { code: '46.75.Z', label: '46.75.Z - Sprzedaż hurtowa wyrobów chemicznych', section: 'G', division: '46' },
  { code: '46.76.Z', label: '46.76.Z - Sprzedaż hurtowa pozostałych półproduktów', section: 'G', division: '46' },
  { code: '46.77.Z', label: '46.77.Z - Sprzedaż hurtowa odpadów i złomu', section: 'G', division: '46' },
  { code: '46.90.Z', label: '46.90.Z - Sprzedaż hurtowa niewyspecjalizowana', section: 'G', division: '46' },
  { code: '47.11.Z', label: '47.11.Z - Sprzedaż detaliczna prowadzona w niewyspecjalizowanych sklepach z przewagą żywności, napojów i wyrobów tytoniowych', section: 'G', division: '47' },
  { code: '47.19.Z', label: '47.19.Z - Pozostała sprzedaż detaliczna prowadzona w niewyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.21.Z', label: '47.21.Z - Sprzedaż detaliczna owoców i warzyw prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.22.Z', label: '47.22.Z - Sprzedaż detaliczna mięsa i wyrobów z mięsa prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.23.Z', label: '47.23.Z - Sprzedaż detaliczna ryb, skorupiaków i mięczaków prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.24.Z', label: '47.24.Z - Sprzedaż detaliczna pieczywa, ciast, wyrobów ciastkarskich i cukierniczych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.25.Z', label: '47.25.Z - Sprzedaż detaliczna napojów alkoholowych i bezalkoholowych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.26.Z', label: '47.26.Z - Sprzedaż detaliczna wyrobów tytoniowych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.29.Z', label: '47.29.Z - Sprzedaż detaliczna pozostałej żywności prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.30.Z', label: '47.30.Z - Sprzedaż detaliczna paliw do pojazdów silnikowych na stacjach paliw', section: 'G', division: '47' },
  { code: '47.41.Z', label: '47.41.Z - Sprzedaż detaliczna komputerów, urządzeń peryferyjnych i oprogramowania prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.42.Z', label: '47.42.Z - Sprzedaż detaliczna sprzętu telekomunikacyjnego prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.43.Z', label: '47.43.Z - Sprzedaż detaliczna sprzętu audiowizualnego prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.51.Z', label: '47.51.Z - Sprzedaż detaliczna wyrobów tekstylnych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.52.Z', label: '47.52.Z - Sprzedaż detaliczna drobnych wyrobów metalowych, farb i szkła prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.53.Z', label: '47.53.Z - Sprzedaż detaliczna dywanów, chodników i innych pokryć podłogowych oraz pokryć ściennych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.54.Z', label: '47.54.Z - Sprzedaż detaliczna elektrycznego sprzętu gospodarstwa domowego prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.59.Z', label: '47.59.Z - Sprzedaż detaliczna mebli, sprzętu oświetleniowego i pozostałych artykułów użytku domowego prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.61.Z', label: '47.61.Z - Sprzedaż detaliczna książek prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.62.Z', label: '47.62.Z - Sprzedaż detaliczna gazet i artykułów piśmiennych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.63.Z', label: '47.63.Z - Sprzedaż detaliczna nagrań dźwiękowych i audiowizualnych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.64.Z', label: '47.64.Z - Sprzedaż detaliczna sprzętu sportowego prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.65.Z', label: '47.65.Z - Sprzedaż detaliczna gier i zabawek prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.71.Z', label: '47.71.Z - Sprzedaż detaliczna odzieży prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.72.Z', label: '47.72.Z - Sprzedaż detaliczna obuwia i wyrobów skórzanych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.73.Z', label: '47.73.Z - Sprzedaż detaliczna wyrobów farmaceutycznych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.74.Z', label: '47.74.Z - Sprzedaż detaliczna wyrobów medycznych, włączając ortopedyczne, prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.75.Z', label: '47.75.Z - Sprzedaż detaliczna kosmetyków i artykułów toaletowych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.76.Z', label: '47.76.Z - Sprzedaż detaliczna kwiatów, roślin, nasion, nawozów, żywych zwierząt domowych, karmy dla zwierząt domowych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.77.Z', label: '47.77.Z - Sprzedaż detaliczna zegarków, zegarów i biżuterii prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.78.Z', label: '47.78.Z - Sprzedaż detaliczna pozostałych nowych wyrobów prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.79.Z', label: '47.79.Z - Sprzedaż detaliczna artykułów używanych prowadzona w wyspecjalizowanych sklepach', section: 'G', division: '47' },
  { code: '47.81.Z', label: '47.81.Z - Sprzedaż detaliczna żywności, napojów i wyrobów tytoniowych prowadzona na straganach i targowiskach', section: 'G', division: '47' },
  { code: '47.82.Z', label: '47.82.Z - Sprzedaż detaliczna wyrobów tekstylnych, odzieży i obuwia prowadzona na straganach i targowiskach', section: 'G', division: '47' },
  { code: '47.89.Z', label: '47.89.Z - Sprzedaż detaliczna pozostałych wyrobów prowadzona na straganach i targowiskach', section: 'G', division: '47' },
  { code: '47.91.Z', label: '47.91.Z - Sprzedaż detaliczna prowadzona przez domy sprzedaży wysyłkowej lub Internet', section: 'G', division: '47' },
  { code: '47.99.Z', label: '47.99.Z - Pozostała sprzedaż detaliczna prowadzona poza siecią sklepową, straganami i targowiskami', section: 'G', division: '47' },
  { code: '49.10.Z', label: '49.10.Z - Transport kolejowy pasażerski międzymiastowy', section: 'H', division: '49' },
  { code: '49.20.Z', label: '49.20.Z - Transport kolejowy towarów', section: 'H', division: '49' },
  { code: '49.31.Z', label: '49.31.Z - Transport lądowy pasażerski, miejski i podmiejski', section: 'H', division: '49' },
  { code: '49.32.Z', label: '49.32.Z - Działalność taksówek osobowych', section: 'H', division: '49' },
  { code: '49.39.Z', label: '49.39.Z - Pozostały transport lądowy pasażerski, gdzie indziej niesklasyfikowany', section: 'H', division: '49' },
  { code: '49.41.Z', label: '49.41.Z - Transport drogowy towarów', section: 'H', division: '49' },
  { code: '49.42.Z', label: '49.42.Z - Działalność usługowa związana z przeprowadzkami', section: 'H', division: '49' },
  { code: '49.50.A', label: '49.50.A - Transport rurociągami paliw gazowych', section: 'H', division: '49' },
  { code: '49.50.B', label: '49.50.B - Transport rurociągowy pozostałych towarów', section: 'H', division: '49' },
  { code: '50.10.Z', label: '50.10.Z - Transport morski i przybrzeżny pasażerski', section: 'H', division: '50' },
  { code: '50.20.Z', label: '50.20.Z - Transport morski i przybrzeżny towarów', section: 'H', division: '50' },
  { code: '50.30.Z', label: '50.30.Z - Transport wodny śródlądowy pasażerski', section: 'H', division: '50' },
  { code: '50.40.Z', label: '50.40.Z - Transport wodny śródlądowy towarów', section: 'H', division: '50' },
  { code: '51.10.Z', label: '51.10.Z - Transport lotniczy pasażerski', section: 'H', division: '51' },
  { code: '51.21.Z', label: '51.21.Z - Transport lotniczy towarów', section: 'H', division: '51' },
  { code: '51.22.Z', label: '51.22.Z - Transport kosmiczny', section: 'H', division: '51' },
  { code: '52.10.A', label: '52.10.A - Magazynowanie i przechowywanie paliw gazowych', section: 'H', division: '52' },
  { code: '52.10.B', label: '52.10.B - Magazynowanie i przechowywanie pozostałych towarów', section: 'H', division: '52' },
  { code: '52.21.Z', label: '52.21.Z - Działalność usługowa wspomagająca transport lądowy', section: 'H', division: '52' },
  { code: '52.22.A', label: '52.22.A - Działalność usługowa wspomagająca transport morski', section: 'H', division: '52' },
  { code: '52.22.B', label: '52.22.B - Działalność usługowa wspomagająca transport śródlądowy', section: 'H', division: '52' },
  { code: '52.23.Z', label: '52.23.Z - Działalność usługowa wspomagająca transport lotniczy', section: 'H', division: '52' },
  { code: '52.24.A', label: '52.24.A - Przeładunek towarów w portach morskich', section: 'H', division: '52' },
  { code: '52.24.B', label: '52.24.B - Przeładunek towarów w portach śródlądowych', section: 'H', division: '52' },
  { code: '52.24.C', label: '52.24.C - Przeładunek towarów w pozostałych punktach przeładunkowych', section: 'H', division: '52' },
  { code: '52.29.A', label: '52.29.A - Działalność morskich agencji transportowych', section: 'H', division: '52' },
  { code: '52.29.B', label: '52.29.B - Działalność śródlądowych agencji transportowych', section: 'H', division: '52' },
  { code: '52.29.C', label: '52.29.C - Działalność pozostałych agencji transportowych', section: 'H', division: '52' },
  { code: '53.10.Z', label: '53.10.Z - Działalność pocztowa objęta obowiązkiem świadczenia usług powszechnych (operatora publicznego)', section: 'H', division: '53' },
  { code: '53.20.Z', label: '53.20.Z - Pozostała działalność pocztowa i kurierska', section: 'H', division: '53' },
  { code: '55.10.Z', label: '55.10.Z - Hotele i podobne obiekty zakwaterowania', section: 'I', division: '55' },
  { code: '55.20.Z', label: '55.20.Z - Obiekty noclegowe turystyczne i miejsca krótkotrwałego zakwaterowania', section: 'I', division: '55' },
  { code: '55.30.Z', label: '55.30.Z - Pola kempingowe (włączając pola dla pojazdów kempingowych) i pola namiotowe', section: 'I', division: '55' },
  { code: '55.90.Z', label: '55.90.Z - Pozostałe zakwaterowanie', section: 'I', division: '55' },
  { code: '56.10.A', label: '56.10.A - Restauracje i inne stałe placówki gastronomiczne', section: 'I', division: '56' },
  { code: '56.10.B', label: '56.10.B - Ruchome placówki gastronomiczne', section: 'I', division: '56' },
  { code: '56.21.Z', label: '56.21.Z - Przygotowywanie i dostarczanie żywności dla odbiorców zewnętrznych (katering)', section: 'I', division: '56' },
  { code: '56.29.Z', label: '56.29.Z - Pozostała usługowa działalność gastronomiczna', section: 'I', division: '56' },
  { code: '56.30.Z', label: '56.30.Z - Przygotowywanie i podawanie napojów', section: 'I', division: '56' },
  { code: '58.11.Z', label: '58.11.Z - Wydawanie książek', section: 'J', division: '58' },
  { code: '58.12.Z', label: '58.12.Z - Wydawanie wykazów oraz list (np. adresowych, telefonicznych)', section: 'J', division: '58' },
  { code: '58.13.Z', label: '58.13.Z - Wydawanie gazet', section: 'J', division: '58' },
  { code: '58.14.Z', label: '58.14.Z - Wydawanie czasopism i pozostałych periodyków', section: 'J', division: '58' },
  { code: '58.19.Z', label: '58.19.Z - Pozostała działalność wydawnicza', section: 'J', division: '58' },
  { code: '58.21.Z', label: '58.21.Z - Działalność wydawnicza w zakresie gier komputerowych', section: 'J', division: '58' },
  { code: '58.29.Z', label: '58.29.Z - Działalność wydawnicza w zakresie pozostałego oprogramowania', section: 'J', division: '58' },
  { code: '59.11.Z', label: '59.11.Z - Działalność związana z produkcją filmów, nagrań wideo i programów telewizyjnych', section: 'J', division: '59' },
  { code: '59.12.Z', label: '59.12.Z - Działalność postprodukcyjna związana z filmami, nagraniami wideo i programami telewizyjnymi', section: 'J', division: '59' },
  { code: '59.13.Z', label: '59.13.Z - Działalność związana z dystrybucją filmów, nagrań wideo i programów telewizyjnych', section: 'J', division: '59' },
  { code: '59.14.Z', label: '59.14.Z - Działalność związana z projekcją filmów', section: 'J', division: '59' },
  { code: '59.20.Z', label: '59.20.Z - Działalność w zakresie nagrań dźwiękowych i muzycznych', section: 'J', division: '59' },
  { code: '60.10.Z', label: '60.10.Z - Nadawanie programów radiofonicznych', section: 'J', division: '60' },
  { code: '60.20.Z', label: '60.20.Z - Nadawanie programów telewizyjnych ogólnodostępnych i abonamentowych', section: 'J', division: '60' },
  { code: '61.10.Z', label: '61.10.Z - Działalność w zakresie telekomunikacji przewodowej', section: 'J', division: '61' },
  { code: '61.20.Z', label: '61.20.Z - Działalność w zakresie telekomunikacji bezprzewodowej, z wyłączeniem telekomunikacji satelitarnej', section: 'J', division: '61' },
  { code: '61.30.Z', label: '61.30.Z - Działalność w zakresie telekomunikacji satelitarnej', section: 'J', division: '61' },
  { code: '61.90.Z', label: '61.90.Z - Działalność w zakresie pozostałej telekomunikacji', section: 'J', division: '61' },
  { code: '62.01.Z', label: '62.01.Z - Działalność związana z oprogramowaniem', section: 'J', division: '62' },
  { code: '62.02.Z', label: '62.02.Z - Działalność związana z doradztwem w zakresie informatyki', section: 'J', division: '62' },
  { code: '62.03.Z', label: '62.03.Z - Działalność związana z zarządzaniem urządzeniami informatycznymi', section: 'J', division: '62' },
  { code: '62.09.Z', label: '62.09.Z - Pozostała działalność usługowa w zakresie technologii informatycznych i komputerowych', section: 'J', division: '62' },
  { code: '63.11.Z', label: '63.11.Z - Przetwarzanie danych; zarządzanie stronami internetowymi (hosting) i podobna działalność', section: 'J', division: '63' },
  { code: '63.12.Z', label: '63.12.Z - Działalność portali internetowych', section: 'J', division: '63' },
  { code: '63.91.Z', label: '63.91.Z - Działalność agencji informacyjnych', section: 'J', division: '63' },
  { code: '63.99.Z', label: '63.99.Z - Pozostała działalność usługowa w zakresie informacji, gdzie indziej niesklasyfikowana', section: 'J', division: '63' },
  { code: '64.11.Z', label: '64.11.Z - Działalność banku centralnego', section: 'K', division: '64' },
  { code: '64.19.Z', label: '64.19.Z - Pozostałe pośrednictwo pieniężne', section: 'K', division: '64' },
  { code: '64.20.Z', label: '64.20.Z - Działalność holdingów finansowych', section: 'K', division: '64' },
  { code: '64.30.Z', label: '64.30.Z - Działalność trustów, funduszów i podobnych instytucji finansowych', section: 'K', division: '64' },
  { code: '64.91.Z', label: '64.91.Z - Leasing finansowy', section: 'K', division: '64' },
  { code: '64.92.Z', label: '64.92.Z - Pozostałe formy udzielania kredytów', section: 'K', division: '64' },
  { code: '64.99.Z', label: '64.99.Z - Pozostała finansowa działalność usługowa, gdzie indziej niesklasyfikowana, z wyłączeniem ubezpieczeń i funduszów emerytalnych', section: 'K', division: '64' },
  { code: '65.11.Z', label: '65.11.Z - Ubezpieczenia na życie', section: 'K', division: '65' },
  { code: '65.12.Z', label: '65.12.Z - Pozostałe ubezpieczenia osobowe oraz ubezpieczenia majątkowe', section: 'K', division: '65' },
  { code: '65.20.Z', label: '65.20.Z - Reasekuracja', section: 'K', division: '65' },
  { code: '65.30.Z', label: '65.30.Z - Fundusze emerytalne', section: 'K', division: '65' },
  { code: '66.11.Z', label: '66.11.Z - Zarządzanie rynkami finansowymi', section: 'K', division: '66' },
  { code: '66.12.Z', label: '66.12.Z - Działalność maklerska związana z rynkiem papierów wartościowych i towarów giełdowych', section: 'K', division: '66' },
  { code: '66.19.Z', label: '66.19.Z - Pozostała działalność wspomagająca usługi finansowe, z wyłączeniem ubezpieczeń i funduszów emerytalnych', section: 'K', division: '66' },
  { code: '66.21.Z', label: '66.21.Z - Działalność związana z oceną ryzyka i szacowaniem poniesionych strat', section: 'K', division: '66' },
  { code: '66.22.Z', label: '66.22.Z - Działalność agentów i brokerów ubezpieczeniowych', section: 'K', division: '66' },
  { code: '66.29.Z', label: '66.29.Z - Pozostała działalność wspomagająca ubezpieczenia i fundusze emerytalne', section: 'K', division: '66' },
  { code: '66.30.Z', label: '66.30.Z - Działalność związana z zarządzaniem funduszami', section: 'K', division: '66' },
  { code: '68.10.Z', label: '68.10.Z - Kupno i sprzedaż nieruchomości na własny rachunek', section: 'L', division: '68' },
  { code: '68.20.Z', label: '68.20.Z - Wynajem i zarządzanie nieruchomościami własnymi lub dzierżawionymi', section: 'L', division: '68' },
  { code: '68.31.Z', label: '68.31.Z - Pośrednictwo w obrocie nieruchomościami', section: 'L', division: '68' },
  { code: '68.32.Z', label: '68.32.Z - Zarządzanie nieruchomościami wykonywane na zlecenie', section: 'L', division: '68' },
  { code: '69.10.Z', label: '69.10.Z - Działalność prawnicza', section: 'M', division: '69' },
  { code: '69.20.Z', label: '69.20.Z - Działalność rachunkowo-księgowa; doradztwo podatkowe', section: 'M', division: '69' },
  { code: '70.10.Z', label: '70.10.Z - Działalność firm centralnych (head offices) i holdingów, z wyłączeniem holdingów finansowych', section: 'M', division: '70' },
  { code: '70.21.Z', label: '70.21.Z - Stosunki międzyludzkie (public relations) i komunikacja', section: 'M', division: '70' },
  { code: '70.22.Z', label: '70.22.Z - Pozostałe doradztwo w zakresie prowadzenia działalności gospodarczej i zarządzania', section: 'M', division: '70' },
  { code: '71.11.Z', label: '71.11.Z - Działalność w zakresie architektury', section: 'M', division: '71' },
  { code: '71.12.Z', label: '71.12.Z - Działalność w zakresie inżynierii i związane z nią doradztwo techniczne', section: 'M', division: '71' },
  { code: '71.20.A', label: '71.20.A - Badania i analizy związane z jakością żywności', section: 'M', division: '71' },
  { code: '71.20.B', label: '71.20.B - Pozostałe badania i analizy techniczne', section: 'M', division: '71' },
  { code: '72.11.Z', label: '72.11.Z - Badania naukowe i prace rozwojowe w dziedzinie biotechnologii', section: 'M', division: '72' },
  { code: '72.19.Z', label: '72.19.Z - Badania naukowe i prace rozwojowe w dziedzinie pozostałych nauk przyrodniczych i technicznych', section: 'M', division: '72' },
  { code: '72.20.Z', label: '72.20.Z - Badania naukowe i prace rozwojowe w dziedzinie nauk społecznych i humanistycznych', section: 'M', division: '72' },
  { code: '73.11.Z', label: '73.11.Z - Działalność agencji reklamowych', section: 'M', division: '73' },
  { code: '73.12.A', label: '73.12.A - Pośrednictwo w sprzedaży czasu i miejsca na cele reklamowe w radio i telewizji', section: 'M', division: '73' },
  { code: '73.12.B', label: '73.12.B - Pośrednictwo w sprzedaży miejsca na cele reklamowe w mediach drukowanych', section: 'M', division: '73' },
  { code: '73.12.C', label: '73.12.C - Pośrednictwo w sprzedaży miejsca na cele reklamowe w mediach elektronicznych (Internet)', section: 'M', division: '73' },
  { code: '73.12.D', label: '73.12.D - Pośrednictwo w sprzedaży miejsca na cele reklamowe w pozostałych mediach', section: 'M', division: '73' },
  { code: '73.20.Z', label: '73.20.Z - Badanie rynku i opinii publicznej', section: 'M', division: '73' },
  { code: '74.10.Z', label: '74.10.Z - Działalność w zakresie specjalistycznego projektowania', section: 'M', division: '74' },
  { code: '74.20.Z', label: '74.20.Z - Działalność fotograficzna', section: 'M', division: '74' },
  { code: '74.30.Z', label: '74.30.Z - Działalność związana z tłumaczeniami', section: 'M', division: '74' },
  { code: '74.90.Z', label: '74.90.Z - Pozostała działalność profesjonalna, naukowa i techniczna, gdzie indziej niesklasyfikowana', section: 'M', division: '74' },
  { code: '75.00.Z', label: '75.00.Z - DZIAŁALNOŚĆ WETERYNARYJNA', section: 'M', division: '75' },
  { code: '77.11.Z', label: '77.11.Z - Wynajem i dzierżawa samochodów osobowych i furgonetek', section: 'N', division: '77' },
  { code: '77.12.Z', label: '77.12.Z - Wynajem i dzierżawa pozostałych pojazdów samochodowych, z wyłączeniem motocykli', section: 'N', division: '77' },
  { code: '77.21.Z', label: '77.21.Z - Wypożyczanie i dzierżawa sprzętu rekreacyjnego i sportowego', section: 'N', division: '77' },
  { code: '77.22.Z', label: '77.22.Z - Wypożyczanie kaset wideo, płyt CD, DVD itp.', section: 'N', division: '77' },
  { code: '77.29.Z', label: '77.29.Z - Wypożyczanie i dzierżawa pozostałych artykułów użytku osobistego i domowego', section: 'N', division: '77' },
  { code: '77.31.Z', label: '77.31.Z - Wynajem i dzierżawa maszyn i urządzeń rolniczych', section: 'N', division: '77' },
  { code: '77.32.Z', label: '77.32.Z - Wynajem i dzierżawa maszyn i urządzeń budowlanych', section: 'N', division: '77' },
  { code: '77.33.Z', label: '77.33.Z - Wynajem i dzierżawa maszyn i urządzeń biurowych, włączając komputery', section: 'N', division: '77' },
  { code: '77.34.Z', label: '77.34.Z - Wynajem i dzierżawa środków transportu wodnego', section: 'N', division: '77' },
  { code: '77.35.Z', label: '77.35.Z - Wynajem i dzierżawa środków transportu lotniczego', section: 'N', division: '77' },
  { code: '77.39.Z', label: '77.39.Z - Wynajem i dzierżawa pozostałych maszyn, urządzeń oraz dóbr materialnych, gdzie indziej niesklasyfikowane', section: 'N', division: '77' },
  { code: '77.40.Z', label: '77.40.Z - Dzierżawa własności intelektualnej i podobnych produktów, z wyłączeniem prac chronionych prawem autorskim', section: 'N', division: '77' },
  { code: '78.10.Z', label: '78.10.Z - Działalność związana z wyszukiwaniem miejsc pracy i pozyskiwaniem pracowników', section: 'N', division: '78' },
  { code: '78.20.Z', label: '78.20.Z - Działalność agencji pracy tymczasowej', section: 'N', division: '78' },
  { code: '78.30.Z', label: '78.30.Z - Pozostała działalność związana z udostępnianiem pracowników', section: 'N', division: '78' },
  { code: '79.11.A', label: '79.11.A - Działalność agentów turystycznych', section: 'N', division: '79' },
  { code: '79.11.B', label: '79.11.B - Działalność pośredników turystycznych', section: 'N', division: '79' },
  { code: '79.12.Z', label: '79.12.Z - Działalność organizatorów turystyki', section: 'N', division: '79' },
  { code: '79.90.A', label: '79.90.A - Działalność pilotów wycieczek i przewodników turystycznych', section: 'N', division: '79' },
  { code: '79.90.B', label: '79.90.B - Działalność w zakresie informacji turystycznej', section: 'N', division: '79' },
  { code: '79.90.C', label: '79.90.C - Pozostała działalność usługowa w zakresie rezerwacji, gdzie indziej niesklasyfikowana', section: 'N', division: '79' },
  { code: '80.10.Z', label: '80.10.Z - Działalność ochroniarska, z wyłączeniem obsługi systemów bezpieczeństwa', section: 'N', division: '80' },
  { code: '80.20.Z', label: '80.20.Z - Działalność ochroniarska w zakresie obsługi systemów bezpieczeństwa', section: 'N', division: '80' },
  { code: '80.30.Z', label: '80.30.Z - Działalność detektywistyczna', section: 'N', division: '80' },
  { code: '81.10.Z', label: '81.10.Z - Działalność pomocnicza związana z utrzymaniem porządku w budynkach', section: 'N', division: '81' },
  { code: '81.21.Z', label: '81.21.Z - Niespecjalistyczne sprzątanie budynków i obiektów przemysłowych', section: 'N', division: '81' },
  { code: '81.22.Z', label: '81.22.Z - Specjalistyczne sprzątanie budynków i obiektów przemysłowych', section: 'N', division: '81' },
  { code: '81.29.Z', label: '81.29.Z - Pozostałe sprzątanie', section: 'N', division: '81' },
  { code: '81.30.Z', label: '81.30.Z - Działalność usługowa związana z zagospodarowaniem terenów zieleni', section: 'N', division: '81' },
  { code: '82.11.Z', label: '82.11.Z - Działalność usługowa związana z administracyjną obsługą biura', section: 'N', division: '82' },
  { code: '82.19.Z', label: '82.19.Z - Wykonywanie fotokopii, przygotowywanie dokumentów i pozostała specjalistyczna działalność wspomagająca prowadzenie biura', section: 'N', division: '82' },
  { code: '82.20.Z', label: '82.20.Z - Działalność centrów telefonicznych (call center)', section: 'N', division: '82' },
  { code: '82.30.Z', label: '82.30.Z - Działalność związana z organizacją targów, wystaw i kongresów', section: 'N', division: '82' },
  { code: '82.91.Z', label: '82.91.Z - Działalność świadczona przez agencje inkasa i biura kredytowe', section: 'N', division: '82' },
  { code: '82.92.Z', label: '82.92.Z - Działalność związana z pakowaniem', section: 'N', division: '82' },
  { code: '82.99.Z', label: '82.99.Z - Pozostała działalność wspomagająca prowadzenie działalności gospodarczej, gdzie indziej niesklasyfikowana', section: 'N', division: '82' },
  { code: '84.11.Z', label: '84.11.Z - Kierowanie podstawowymi rodzajami działalności publicznej', section: 'O', division: '84' },
  { code: '84.12.Z', label: '84.12.Z - Kierowanie w zakresie działalności związanej z ochroną zdrowia, edukacją, kulturą oraz pozostałymi usługami społecznymi, z wyłączeniem zabezpieczeń społecznych', section: 'O', division: '84' },
  { code: '84.13.Z', label: '84.13.Z - Kierowanie w zakresie efektywności gospodarowania', section: 'O', division: '84' },
  { code: '84.21.Z', label: '84.21.Z - Sprawy zagraniczne', section: 'O', division: '84' },
  { code: '84.22.Z', label: '84.22.Z - Obrona narodowa', section: 'O', division: '84' },
  { code: '84.23.Z', label: '84.23.Z - Wymiar sprawiedliwości', section: 'O', division: '84' },
  { code: '84.24.Z', label: '84.24.Z - Bezpieczeństwo państwa, porządek i bezpieczeństwo publiczne', section: 'O', division: '84' },
  { code: '84.25.Z', label: '84.25.Z - Ochrona przeciwpożarowa', section: 'O', division: '84' },
  { code: '84.30.Z', label: '84.30.Z - Obowiązkowe zabezpieczenia społeczne', section: 'O', division: '84' },
  { code: '85.10.Z', label: '85.10.Z - Placówki wychowania przedszkolnego', section: 'P', division: '85' },
  { code: '85.20.Z', label: '85.20.Z - Szkoły podstawowe', section: 'P', division: '85' },
  { code: '85.31.A', label: '85.31.A - Gimnazja', section: 'P', division: '85' },
  { code: '85.31.B', label: '85.31.B - Licea ogólnokształcące', section: 'P', division: '85' },
  { code: '85.32.A', label: '85.32.A - Technika', section: 'P', division: '85' },
  { code: '85.32.B', label: '85.32.B - Branżowe szkoły I stopnia', section: 'P', division: '85' },
  { code: '85.32.C', label: '85.32.C - Szkoły specjalne przysposabiające do pracy', section: 'P', division: '85' },
  { code: '85.32.D', label: '85.32.D - Branżowe szkoły II stopnia', section: 'P', division: '85' },
  { code: '85.41.A', label: '85.41.A - Szkoły policealne', section: 'P', division: '85' },
  { code: '85.41.B', label: '85.41.B - Kolegia pracowników służb społecznych', section: 'P', division: '85' },
  { code: '85.41.C', label: '85.41.C - Placówki doskonalenia nauczycieli', section: 'P', division: '85' },
  { code: '85.42.A', label: '85.42.A - Zakłady kształcenia nauczycieli i kolegia pracowników służb społecznych', section: 'P', division: '85' },
  { code: '85.42.Z', label: '85.42.Z - Szkoły wyższe', section: 'P', division: '85' },
  { code: '85.51.Z', label: '85.51.Z - Pozaszkolne formy edukacji sportowej oraz zajęć sportowych i rekreacyjnych', section: 'P', division: '85' },
  { code: '85.52.Z', label: '85.52.Z - Pozaszkolne formy edukacji artystycznej', section: 'P', division: '85' },
  { code: '85.53.Z', label: '85.53.Z - Pozaszkolne formy edukacji z zakresu nauki jazdy i pilotażu', section: 'P', division: '85' },
  { code: '85.59.A', label: '85.59.A - Nauka języków obcych', section: 'P', division: '85' },
  { code: '85.59.B', label: '85.59.B - Pozostałe pozaszkolne formy edukacji, gdzie indziej niesklasyfikowane', section: 'P', division: '85' },
  { code: '85.60.Z', label: '85.60.Z - Działalność wspomagająca edukację', section: 'P', division: '85' },
  { code: '86.10.Z', label: '86.10.Z - Działalność szpitali', section: 'Q', division: '86' },
  { code: '86.21.Z', label: '86.21.Z - Praktyka lekarska ogólna', section: 'Q', division: '86' },
  { code: '86.22.Z', label: '86.22.Z - Praktyka lekarska specjalistyczna', section: 'Q', division: '86' },
  { code: '86.23.Z', label: '86.23.Z - Praktyka lekarska dentystyczna', section: 'Q', division: '86' },
  { code: '86.90.A', label: '86.90.A - Działalność fizjoterapeutyczna', section: 'Q', division: '86' },
  { code: '86.90.B', label: '86.90.B - Działalność pogotowia ratunkowego', section: 'Q', division: '86' },
  { code: '86.90.C', label: '86.90.C - Praktyka pielęgniarek i położnych', section: 'Q', division: '86' },
  { code: '86.90.D', label: '86.90.D - Działalność paramedyczna', section: 'Q', division: '86' },
  { code: '86.90.E', label: '86.90.E - Pozostała działalność w zakresie opieki zdrowotnej, gdzie indziej niesklasyfikowana', section: 'Q', division: '86' },
  { code: '87.10.Z', label: '87.10.Z - Pomoc społeczna z zakwaterowaniem zapewniająca opiekę pielęgniarską', section: 'Q', division: '87' },
  { code: '87.20.Z', label: '87.20.Z - Pomoc społeczna z zakwaterowaniem dla osób z zaburzeniami psychicznymi', section: 'Q', division: '87' },
  { code: '87.30.Z', label: '87.30.Z - Pomoc społeczna z zakwaterowaniem dla osób w podeszłym wieku i osób niepełnosprawnych', section: 'Q', division: '87' },
  { code: '87.90.Z', label: '87.90.Z - Pozostała pomoc społeczna z zakwaterowaniem', section: 'Q', division: '87' },
  { code: '88.10.Z', label: '88.10.Z - Pomoc społeczna bez zakwaterowania dla osób w podeszłym wieku i osób niepełnosprawnych', section: 'Q', division: '88' },
  { code: '88.91.Z', label: '88.91.Z - Opieka dzienna nad dziećmi', section: 'Q', division: '88' },
  { code: '88.99.Z', label: '88.99.Z - Pozostała pomoc społeczna bez zakwaterowania, gdzie indziej niesklasyfikowana', section: 'Q', division: '88' },
  { code: '90.01.Z', label: '90.01.Z - Działalność związana z wystawianiem przedstawień artystycznych', section: 'R', division: '90' },
  { code: '90.02.Z', label: '90.02.Z - Działalność wspomagająca wystawianie przedstawień artystycznych', section: 'R', division: '90' },
  { code: '90.03.Z', label: '90.03.Z - Artystyczna i literacka działalność twórcza', section: 'R', division: '90' },
  { code: '90.04.Z', label: '90.04.Z - Działalność obiektów kulturalnych', section: 'R', division: '90' },
  { code: '91.01.A', label: '91.01.A - Działalność bibliotek', section: 'R', division: '91' },
  { code: '91.01.B', label: '91.01.B - Działalność archiwów', section: 'R', division: '91' },
  { code: '91.02.Z', label: '91.02.Z - Działalność muzeów', section: 'R', division: '91' },
  { code: '91.03.Z', label: '91.03.Z - Działalność historycznych miejsc i budynków oraz podobnych atrakcji turystycznych', section: 'R', division: '91' },
  { code: '91.04.Z', label: '91.04.Z - Działalność ogrodów botanicznych i zoologicznych oraz obszarów i obiektów ochrony przyrody', section: 'R', division: '91' },
  { code: '92.00.Z', label: '92.00.Z - DZIAŁALNOŚĆ ZWIĄZANA Z GRAMI LOSOWYMI I ZAKŁADAMI WZAJEMNYMI', section: 'R', division: '92' },
  { code: '93.11.Z', label: '93.11.Z - Działalność obiektów sportowych', section: 'R', division: '93' },
  { code: '93.12.Z', label: '93.12.Z - Działalność klubów sportowych', section: 'R', division: '93' },
  { code: '93.13.Z', label: '93.13.Z - Działalność obiektów służących poprawie kondycji fizycznej', section: 'R', division: '93' },
  { code: '93.19.Z', label: '93.19.Z - Pozostała działalność związana ze sportem', section: 'R', division: '93' },
  { code: '93.21.Z', label: '93.21.Z - Działalność wesołych miasteczek i parków rozrywki', section: 'R', division: '93' },
  { code: '93.29.A', label: '93.29.A - Działalność pokojów zagadek, domów strachu, miejsc do tańczenia i w zakresie innych form rozrywki lub rekreacji organizowanych w pomieszczeniach lub w innych miejscach o zamkniętej przestrzeni', section: 'R', division: '93' },
  { code: '93.29.B', label: '93.29.B - Pozostała działalność rozrywkowa i rekreacyjna, gdzie indziej niesklasyfikowana', section: 'R', division: '93' },
  { code: '94.11.Z', label: '94.11.Z - Działalność organizacji komercyjnych i pracodawców', section: 'S', division: '94' },
  { code: '94.12.Z', label: '94.12.Z - Działalność organizacji profesjonalnych', section: 'S', division: '94' },
  { code: '94.20.Z', label: '94.20.Z - Działalność związków zawodowych', section: 'S', division: '94' },
  { code: '94.91.Z', label: '94.91.Z - Działalność organizacji religijnych', section: 'S', division: '94' },
  { code: '94.92.Z', label: '94.92.Z - Działalność organizacji politycznych', section: 'S', division: '94' },
  { code: '94.99.Z', label: '94.99.Z - Działalność pozostałych organizacji członkowskich, gdzie indziej niesklasyfikowana', section: 'S', division: '94' },
  { code: '95.11.Z', label: '95.11.Z - Naprawa i konserwacja komputerów i urządzeń peryferyjnych', section: 'S', division: '95' },
  { code: '95.12.Z', label: '95.12.Z - Naprawa i konserwacja sprzętu (tele)komunikacyjnego', section: 'S', division: '95' },
  { code: '95.21.Z', label: '95.21.Z - Naprawa i konserwacja elektronicznego sprzętu powszechnego użytku', section: 'S', division: '95' },
  { code: '95.22.Z', label: '95.22.Z - Naprawa i konserwacja urządzeń gospodarstwa domowego oraz sprzętu użytku domowego i ogrodniczego', section: 'S', division: '95' },
  { code: '95.23.Z', label: '95.23.Z - Naprawa obuwia i wyrobów skórzanych', section: 'S', division: '95' },
  { code: '95.24.Z', label: '95.24.Z - Naprawa i konserwacja mebli i wyposażenia domowego', section: 'S', division: '95' },
  { code: '95.25.Z', label: '95.25.Z - Naprawa zegarów, zegarków oraz biżuterii', section: 'S', division: '95' },
  { code: '95.29.Z', label: '95.29.Z - Naprawa pozostałych artykułów użytku osobistego i domowego', section: 'S', division: '95' },
  { code: '96.01.Z', label: '96.01.Z - Pranie i czyszczenie wyrobów włókienniczych i futrzarskich', section: 'S', division: '96' },
  { code: '96.02.Z', label: '96.02.Z - Fryzjerstwo i pozostałe zabiegi kosmetyczne', section: 'S', division: '96' },
  { code: '96.03.Z', label: '96.03.Z - Pogrzeby i działalność pokrewna', section: 'S', division: '96' },
  { code: '96.04.Z', label: '96.04.Z - Działalność usługowa związana z poprawą kondycji fizycznej', section: 'S', division: '96' },
  { code: '96.09.Z', label: '96.09.Z - Pozostała działalność usługowa, gdzie indziej niesklasyfikowana', section: 'S', division: '96' },
  { code: '97.00.Z', label: '97.00.Z - GOSPODARSTWA DOMOWE ZATRUDNIAJĄCE PRACOWNIKÓW', section: 'T', division: '97' },
  { code: '98.10.Z', label: '98.10.Z - Gospodarstwa domowe produkujące wyroby na własne potrzeby', section: 'T', division: '98' },
  { code: '98.20.Z', label: '98.20.Z - Gospodarstwa domowe świadczące usługi na własne potrzeby', section: 'T', division: '98' },
  { code: '99.00.Z', label: '99.00.Z - ORGANIZACJE I ZESPOŁY EKSTERYTORIALNE', section: 'U', division: '99' },
] as const;

export type PkdCode = typeof PKD_CODES[number]["code"];

// Helper to get PKD codes grouped by section for UI
export function getPkdCodesBySection() {
  const grouped: Record<PkdSection, typeof PKD_CODES[number][]> = {} as Record<PkdSection, typeof PKD_CODES[number][]>;
  for (const pkd of PKD_CODES) {
    const section = pkd.section as PkdSection;
    if (!grouped[section]) {
      grouped[section] = [];
    }
    grouped[section].push(pkd);
  }
  return grouped;
}
