export enum OfferErrorCode {
  // Lead errors
  LEAD_NOT_FOUND = 'LEAD_NOT_FOUND',
  LEAD_ALREADY_CONVERTED = 'LEAD_ALREADY_CONVERTED',
  LEAD_INVALID_STATUS_TRANSITION = 'LEAD_INVALID_STATUS_TRANSITION',
  LEAD_HAS_OFFERS = 'LEAD_HAS_OFFERS',

  // Offer Template errors
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_FILE_NOT_FOUND = 'TEMPLATE_FILE_NOT_FOUND',
  TEMPLATE_INVALID_FILE_TYPE = 'TEMPLATE_INVALID_FILE_TYPE',
  TEMPLATE_HAS_OFFERS = 'TEMPLATE_HAS_OFFERS',

  // Client errors (within offers context)
  CLIENT_NOT_FOUND = 'CLIENT_NOT_FOUND',

  // Offer errors
  OFFER_NOT_FOUND = 'OFFER_NOT_FOUND',
  OFFER_INVALID_STATUS_TRANSITION = 'OFFER_INVALID_STATUS_TRANSITION',
  OFFER_CANNOT_MODIFY = 'OFFER_CANNOT_MODIFY',
  OFFER_NO_RECIPIENT = 'OFFER_NO_RECIPIENT',
  OFFER_DOCUMENT_NOT_GENERATED = 'OFFER_DOCUMENT_NOT_GENERATED',
  OFFER_ALREADY_SENT = 'OFFER_ALREADY_SENT',
  OFFER_RECIPIENT_NO_EMAIL = 'OFFER_RECIPIENT_NO_EMAIL',

  // Document generation errors
  DOCUMENT_GENERATION_FAILED = 'DOCUMENT_GENERATION_FAILED',
  DOCUMENT_TEMPLATE_INVALID = 'DOCUMENT_TEMPLATE_INVALID',

  // Email errors
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',
  EMAIL_CONFIGURATION_MISSING = 'EMAIL_CONFIGURATION_MISSING',
}
