export enum OfferActivityType {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  DOCUMENT_GENERATED = 'DOCUMENT_GENERATED',
  EMAIL_SENT = 'EMAIL_SENT',
  VIEWED = 'VIEWED',
  DUPLICATED = 'DUPLICATED',
  COMMENT_ADDED = 'COMMENT_ADDED',
}
