/**
 * Centralized error codes for clients module
 * Format: [ENTITY]_[NUMBER]
 */
export enum ClientErrorCode {
  // Client errors (CLIENT_00X)
  CLIENT_NOT_FOUND = 'CLIENT_001',
  CLIENT_ALREADY_EXISTS = 'CLIENT_002',
  CLIENT_DELETE_FAILED = 'CLIENT_003',
  CLIENT_UPDATE_FAILED = 'CLIENT_004',
  CLIENT_BATCH_OPERATION_FAILED = 'CLIENT_005',

  // Icon errors (ICON_00X)
  ICON_NOT_FOUND = 'ICON_001',
  ICON_UPLOAD_FAILED = 'ICON_002',
  ICON_INVALID_TYPE = 'ICON_003',
  ICON_FILE_TOO_LARGE = 'ICON_004',
  ICON_ASSIGNMENT_FAILED = 'ICON_005',

  // Field errors (FIELD_00X)
  FIELD_NOT_FOUND = 'FIELD_001',
  FIELD_VALIDATION_FAILED = 'FIELD_002',
  FIELD_REQUIRED = 'FIELD_003',
  FIELD_INVALID_TYPE = 'FIELD_004',
  FIELD_ENUM_INVALID = 'FIELD_005',

  // Auto-assign errors (ASSIGN_00X)
  AUTO_ASSIGN_EVALUATION_FAILED = 'ASSIGN_001',
  AUTO_ASSIGN_CONDITION_INVALID = 'ASSIGN_002',
  AUTO_ASSIGN_BATCH_FAILED = 'ASSIGN_003',

  // Delete request errors (DELETE_00X)
  DELETE_REQUEST_NOT_FOUND = 'DELETE_001',
  DELETE_REQUEST_ALREADY_PROCESSED = 'DELETE_002',
  DELETE_REQUEST_FAILED = 'DELETE_003',

  // Authorization errors
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // System errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
